// Ported verbatim from legacy client/src/data/charityData.ts. Real data —
// 98 real, named charities scored across 7 weighted dimensions, unifying
// GiveWell/Charity Navigator/CharityWatch/Candid ratings. Plain module,
// imported by both the Server Component pages and the client-side
// rankings/scorecard/evaluators explorer.

export type CloakStatus = "clear" | "mostly-clear" | "hazy" | "opaque";
export type Grade = "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D" | "F";
export type GiveWellStatus = "top" | "standout" | "reviewed" | null;
export type CNRating = 4 | 3 | 2 | 1 | 0 | null;
export type CNGrade = "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "D" | "F" | null;
export type CandidSeal = "platinum" | "gold" | "silver" | "bronze" | null;

export type Sector =
  | "Global Health"
  | "Cash Transfers"
  | "Humanitarian"
  | "Global Dev"
  | "Education"
  | "Environment"
  | "Animals"
  | "Children"
  | "Poverty"
  | "Agriculture"
  | "Water & Sanitation"
  | "Mental Health"
  | "Human Rights"
  | "Disaster Relief"
  | "Nutrition"
  | "Technology"
  | "Arts & Culture"
  | "Housing"
  | "Criminal Justice"
  | "Community Dev";

export interface ScoreBreakdown {
  impactOutcomes: number;
  transparency: number;
  dollarEfficiency: number;
  evidenceQuality: number;
  cloakScore: number;
  beneficiaryVoice: number;
  adaptability: number;
}

export interface Charity {
  slug: string;
  name: string;
  sector: Sector;
  totalScore: number;
  grade: Grade;
  scores: ScoreBreakdown;
  cloakStatus: CloakStatus;
  givewell: GiveWellStatus;
  cnStars: CNRating;
  charityWatch: CNGrade;
  candidSeal: CandidSeal;
  donationsM: number;
  founded: number;
  hq: string;
  website: string;
  tagline: string;
  impactMetric: string;
  beneficiaries: string;
}

export const SCORE_WEIGHTS = {
  impactOutcomes: 0.25,
  transparency: 0.2,
  dollarEfficiency: 0.15,
  evidenceQuality: 0.15,
  cloakScore: 0.1,
  beneficiaryVoice: 0.1,
  adaptability: 0.05,
} as const;

export const SCORE_DIMENSIONS: {
  key: keyof ScoreBreakdown;
  label: string;
  weight: number;
  description: string;
}[] = [
  { key: "impactOutcomes", label: "Verified Impact Outcomes", weight: 25, description: "Measurable, third-party-verified results per dollar. Uses DALY, QALY, SROI, cost-per-life-saved." },
  { key: "transparency", label: "Transparency & Disclosure", weight: 20, description: "Full financial disclosure, Candid Platinum Seal, open-data policies, Benford's Law compliance." },
  { key: "dollarEfficiency", label: "Dollar Efficiency", weight: 15, description: "Program expense ratio, fundraising efficiency, charitable commitment percentage." },
  { key: "evidenceQuality", label: "Evidence Quality & Rigor", weight: 15, description: "Randomized controlled trials, peer-reviewed studies, independent evaluations, replication quality." },
  { key: "cloakScore", label: "Cloak-vs-Clear Score", weight: 10, description: "Proprietary transparency metric: do they hide what matters? Benford's Law analysis on financials, disclosure completeness, accessibility of impact data." },
  { key: "beneficiaryVoice", label: "Beneficiary Voice & Feedback", weight: 10, description: "Does the charity listen to the people it serves? Feedback loops, community input, participatory design." },
  { key: "adaptability", label: "Adaptability & Learning", weight: 5, description: "Does the organization learn from failures? Pivot history, program iteration, honest reporting of setbacks." },
];

export interface Evaluator {
  name: string;
  url: string;
  focus: string;
  metric: string;
  limitation: string;
  charityCount: string;
}

export const EVALUATORS: Evaluator[] = [
  { name: "Charity Navigator", url: "https://charitynavigator.org", focus: "Financial Health & Accountability", metric: "0–4 Stars (100pt Encompass)", limitation: "Relies on Form 990; weak on actual outcomes", charityCount: "200,000+" },
  { name: "GiveWell", url: "https://givewell.org", focus: "Cost-Effectiveness & Evidence", metric: "Cost per life saved / DALY", limitation: "Only evaluates ~15 orgs; narrow global health focus", charityCount: "~15" },
  { name: "CharityWatch", url: "https://charitywatch.org", focus: "Financial Efficiency", metric: "A+ to F letter grade", limitation: "Paywalled; small universe (~600 charities)", charityCount: "~600" },
  { name: "Candid/GuideStar", url: "https://guidestar.org", focus: "Transparency & Self-Reporting", metric: "Bronze–Platinum Seal", limitation: "Voluntary disclosure; no performance judgment", charityCount: "1.8M+" },
  { name: "Impact Matters (now Charity Navigator)", url: "https://charitynavigator.org", focus: "Cost-Effectiveness Analysis", metric: "Impact per dollar benchmarks", limitation: "Merged into CN; limited standalone access", charityCount: "Merged" },
  { name: "The Life You Can Save", url: "https://thelifeyoucansave.org", focus: "Evidence-Based Giving", metric: "Curated best-in-class list", limitation: "Very small curated list (~25); no scoring system", charityCount: "~25" },
  { name: "Animal Charity Evaluators", url: "https://animalcharityevaluators.org", focus: "Animal Welfare Impact", metric: "Top / Standout / Effective", limitation: "Animal-only; excludes all human-focused charities", charityCount: "~20" },
  { name: "Giving What We Can", url: "https://givingwhatwecan.org", focus: "Effective Altruism Alignment", metric: "Curated recommendations", limitation: "Heavily EA-aligned; philosophical bias toward global health", charityCount: "~30" },
];

function computeTotal(scores: ScoreBreakdown): number {
  return (
    Math.round(
      (scores.impactOutcomes * SCORE_WEIGHTS.impactOutcomes +
        scores.transparency * SCORE_WEIGHTS.transparency +
        scores.dollarEfficiency * SCORE_WEIGHTS.dollarEfficiency +
        scores.evidenceQuality * SCORE_WEIGHTS.evidenceQuality +
        scores.cloakScore * SCORE_WEIGHTS.cloakScore +
        scores.beneficiaryVoice * SCORE_WEIGHTS.beneficiaryVoice +
        scores.adaptability * SCORE_WEIGHTS.adaptability) *
        10,
    ) / 10
  );
}

function gradeFromScore(score: number): Grade {
  if (score >= 97) return "A+";
  if (score >= 93) return "A";
  if (score >= 90) return "A-";
  if (score >= 87) return "B+";
  if (score >= 83) return "B";
  if (score >= 80) return "B-";
  if (score >= 77) return "C+";
  if (score >= 73) return "C";
  if (score >= 70) return "C-";
  if (score >= 60) return "D";
  return "F";
}

function cloakFromScore(score: number): CloakStatus {
  if (score >= 90) return "clear";
  if (score >= 75) return "mostly-clear";
  if (score >= 55) return "hazy";
  return "opaque";
}

const RAW_CHARITIES: Omit<Charity, "totalScore" | "grade" | "cloakStatus">[] = [
  { slug: "against-malaria-foundation", name: "Against Malaria Foundation", sector: "Global Health", scores: { impactOutcomes: 99, transparency: 98, dollarEfficiency: 99, evidenceQuality: 99, cloakScore: 98, beneficiaryVoice: 95, adaptability: 94 }, givewell: "top", cnStars: 4, charityWatch: "A+", candidSeal: "platinum", donationsM: 85, founded: 2004, hq: "London, UK", website: "https://againstmalaria.com", tagline: "Distributing insecticide-treated bed nets to prevent malaria", impactMetric: "$5 per DALY averted", beneficiaries: "45M nets distributed" },
  { slug: "malaria-consortium", name: "Malaria Consortium", sector: "Global Health", scores: { impactOutcomes: 98, transparency: 97, dollarEfficiency: 98, evidenceQuality: 97, cloakScore: 96, beneficiaryVoice: 93, adaptability: 95 }, givewell: "top", cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 120, founded: 2003, hq: "London, UK", website: "https://malariaconsortium.org", tagline: "Seasonal malaria chemoprevention for children", impactMetric: "$7 per child protected", beneficiaries: "50M children treated" },
  { slug: "helen-keller-international", name: "Helen Keller International", sector: "Global Health", scores: { impactOutcomes: 97, transparency: 95, dollarEfficiency: 96, evidenceQuality: 96, cloakScore: 94, beneficiaryVoice: 93, adaptability: 92 }, givewell: "top", cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 60, founded: 1915, hq: "New York, USA", website: "https://hki.org", tagline: "Vitamin A supplementation preventing childhood blindness and death", impactMetric: "$1 per child supplemented", beneficiaries: "200M people reached" },
  { slug: "sci-foundation", name: "SCI Foundation", sector: "Global Health", scores: { impactOutcomes: 97, transparency: 96, dollarEfficiency: 97, evidenceQuality: 95, cloakScore: 95, beneficiaryVoice: 91, adaptability: 93 }, givewell: "top", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 35, founded: 2002, hq: "London, UK", website: "https://schistosomiasiscontrolinitiative.org", tagline: "Mass deworming programs in sub-Saharan Africa", impactMetric: "$0.50 per treatment", beneficiaries: "200M treatments delivered" },
  { slug: "sightsavers", name: "Sightsavers", sector: "Global Health", scores: { impactOutcomes: 96, transparency: 94, dollarEfficiency: 95, evidenceQuality: 94, cloakScore: 93, beneficiaryVoice: 92, adaptability: 91 }, givewell: "standout", cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 50, founded: 1950, hq: "Haywards Heath, UK", website: "https://sightsavers.org", tagline: "Preventing avoidable blindness and promoting disability rights", impactMetric: "$25 per trachoma surgery", beneficiaries: "2M surgeries performed" },
  { slug: "evidence-action", name: "Evidence Action", sector: "Global Dev", scores: { impactOutcomes: 96, transparency: 96, dollarEfficiency: 96, evidenceQuality: 97, cloakScore: 95, beneficiaryVoice: 90, adaptability: 93 }, givewell: "top", cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 55, founded: 2013, hq: "Washington, DC", website: "https://evidenceaction.org", tagline: "Scaling proven health interventions: deworming and safe water", impactMetric: "$0.30 per deworming treatment", beneficiaries: "280M people reached" },
  { slug: "new-incentives", name: "New Incentives", sector: "Global Health", scores: { impactOutcomes: 97, transparency: 96, dollarEfficiency: 97, evidenceQuality: 96, cloakScore: 95, beneficiaryVoice: 92, adaptability: 94 }, givewell: "top", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 45, founded: 2011, hq: "San Francisco, USA", website: "https://newincentives.org", tagline: "Cash incentives for childhood vaccination in Nigeria", impactMetric: "$25 per additional child vaccinated", beneficiaries: "3M+ infants vaccinated" },
  { slug: "givedirectly", name: "GiveDirectly", sector: "Cash Transfers", scores: { impactOutcomes: 97, transparency: 98, dollarEfficiency: 96, evidenceQuality: 98, cloakScore: 97, beneficiaryVoice: 98, adaptability: 96 }, givewell: "top", cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 340, founded: 2008, hq: "New York, USA", website: "https://givedirectly.org", tagline: "Unconditional cash transfers directly to people in extreme poverty", impactMetric: "$1,000 per household transfer", beneficiaries: "1.5M people served" },
  { slug: "direct-relief", name: "Direct Relief", sector: "Humanitarian", scores: { impactOutcomes: 95, transparency: 97, dollarEfficiency: 98, evidenceQuality: 92, cloakScore: 90, beneficiaryVoice: 88, adaptability: 93 }, givewell: null, cnStars: 4, charityWatch: "A+", candidSeal: "platinum", donationsM: 1800, founded: 1948, hq: "Santa Barbara, USA", website: "https://directrelief.org", tagline: "Medical aid to people affected by poverty and emergencies", impactMetric: "$1.8B in medical supplies", beneficiaries: "100 countries served" },
  { slug: "doctors-without-borders", name: "Doctors Without Borders (MSF)", sector: "Humanitarian", scores: { impactOutcomes: 94, transparency: 93, dollarEfficiency: 90, evidenceQuality: 91, cloakScore: 92, beneficiaryVoice: 90, adaptability: 96 }, givewell: null, cnStars: 4, charityWatch: "A+", candidSeal: "platinum", donationsM: 2100, founded: 1971, hq: "Geneva, Switzerland", website: "https://msf.org", tagline: "Emergency medical care in conflict zones and epidemics", impactMetric: "12M+ outpatient consultations/yr", beneficiaries: "70+ countries" },
  { slug: "international-rescue-committee", name: "International Rescue Committee", sector: "Humanitarian", scores: { impactOutcomes: 92, transparency: 93, dollarEfficiency: 89, evidenceQuality: 91, cloakScore: 88, beneficiaryVoice: 91, adaptability: 93 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 950, founded: 1933, hq: "New York, USA", website: "https://rescue.org", tagline: "Helping people affected by humanitarian crises survive, recover, and rebuild", impactMetric: "26M people reached/yr", beneficiaries: "40+ countries" },
  { slug: "partners-in-health", name: "Partners In Health", sector: "Global Health", scores: { impactOutcomes: 93, transparency: 92, dollarEfficiency: 87, evidenceQuality: 94, cloakScore: 91, beneficiaryVoice: 95, adaptability: 94 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 350, founded: 1987, hq: "Boston, USA", website: "https://pih.org", tagline: "Bringing quality healthcare to the world's poorest communities", impactMetric: "3M+ patients served/yr", beneficiaries: "12 countries" },
  { slug: "the-nature-conservancy", name: "The Nature Conservancy", sector: "Environment", scores: { impactOutcomes: 88, transparency: 91, dollarEfficiency: 82, evidenceQuality: 87, cloakScore: 80, beneficiaryVoice: 78, adaptability: 90 }, givewell: null, cnStars: 3, charityWatch: "A-", candidSeal: "platinum", donationsM: 1200, founded: 1951, hq: "Arlington, USA", website: "https://nature.org", tagline: "Conserving lands and waters on which all life depends", impactMetric: "125M acres protected", beneficiaries: "72 countries" },
  { slug: "rainforest-alliance", name: "Rainforest Alliance", sector: "Environment", scores: { impactOutcomes: 86, transparency: 89, dollarEfficiency: 84, evidenceQuality: 83, cloakScore: 82, beneficiaryVoice: 80, adaptability: 88 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "gold", donationsM: 65, founded: 1987, hq: "New York, USA", website: "https://rainforest-alliance.org", tagline: "Working at the intersection of business, agriculture, and forests", impactMetric: "6M+ farmers certified", beneficiaries: "70+ countries" },
  { slug: "ocean-conservancy", name: "Ocean Conservancy", sector: "Environment", scores: { impactOutcomes: 84, transparency: 88, dollarEfficiency: 83, evidenceQuality: 82, cloakScore: 85, beneficiaryVoice: 76, adaptability: 85 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 45, founded: 1972, hq: "Washington, DC", website: "https://oceanconservancy.org", tagline: "Protecting the ocean from today's greatest global challenges", impactMetric: "350M lbs trash removed", beneficiaries: "Global oceans" },
  { slug: "cool-earth", name: "Cool Earth", sector: "Environment", scores: { impactOutcomes: 89, transparency: 90, dollarEfficiency: 91, evidenceQuality: 85, cloakScore: 92, beneficiaryVoice: 93, adaptability: 87 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 8, founded: 2007, hq: "London, UK", website: "https://coolearth.org", tagline: "Partnering with rainforest communities to halt deforestation", impactMetric: "$0.12 per tonne CO2 saved", beneficiaries: "900K+ acres protected" },
  { slug: "clean-air-task-force", name: "Clean Air Task Force", sector: "Environment", scores: { impactOutcomes: 91, transparency: 89, dollarEfficiency: 93, evidenceQuality: 90, cloakScore: 88, beneficiaryVoice: 72, adaptability: 91 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 40, founded: 1996, hq: "Boston, USA", website: "https://catf.us", tagline: "Pushing for policy and technology to decarbonize the energy system", impactMetric: "$0.10 per tonne CO2 averted", beneficiaries: "Global climate" },
  { slug: "room-to-read", name: "Room to Read", sector: "Education", scores: { impactOutcomes: 90, transparency: 92, dollarEfficiency: 88, evidenceQuality: 89, cloakScore: 91, beneficiaryVoice: 88, adaptability: 87 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 70, founded: 2000, hq: "San Francisco, USA", website: "https://roomtoread.org", tagline: "Literacy and gender equality in education across Asia and Africa", impactMetric: "23M children reached", beneficiaries: "21 countries" },
  { slug: "pratham", name: "Pratham", sector: "Education", scores: { impactOutcomes: 92, transparency: 90, dollarEfficiency: 93, evidenceQuality: 91, cloakScore: 89, beneficiaryVoice: 91, adaptability: 90 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 55, founded: 1995, hq: "Mumbai, India", website: "https://pratham.org", tagline: "Every child in school and learning well", impactMetric: "$15 per child per year", beneficiaries: "60M+ children reached" },
  { slug: "teach-for-all", name: "Teach For All", sector: "Education", scores: { impactOutcomes: 85, transparency: 87, dollarEfficiency: 82, evidenceQuality: 84, cloakScore: 86, beneficiaryVoice: 83, adaptability: 88 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 30, founded: 2007, hq: "New York, USA", website: "https://teachforall.org", tagline: "Developing collective leadership to ensure all children can fulfill their potential", impactMetric: "1M+ students impacted/yr", beneficiaries: "60+ countries" },
  { slug: "charity-water", name: "charity: water", sector: "Water & Sanitation", scores: { impactOutcomes: 88, transparency: 96, dollarEfficiency: 85, evidenceQuality: 83, cloakScore: 97, beneficiaryVoice: 86, adaptability: 84 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 120, founded: 2006, hq: "New York, USA", website: "https://charitywater.org", tagline: "Bringing clean and safe drinking water to people in developing countries", impactMetric: "$40 per person served", beneficiaries: "17M+ people served" },
  { slug: "waterorg", name: "Water.org", sector: "Water & Sanitation", scores: { impactOutcomes: 89, transparency: 91, dollarEfficiency: 92, evidenceQuality: 86, cloakScore: 90, beneficiaryVoice: 84, adaptability: 88 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 45, founded: 1990, hq: "Kansas City, USA", website: "https://water.org", tagline: "Safe water and sanitation through affordable financing", impactMetric: "$5 per person via WaterCredit", beneficiaries: "52M+ people reached" },
  { slug: "evidence-action-dispensers", name: "Dispensers for Safe Water (Evidence Action)", sector: "Water & Sanitation", scores: { impactOutcomes: 93, transparency: 94, dollarEfficiency: 95, evidenceQuality: 92, cloakScore: 93, beneficiaryVoice: 87, adaptability: 90 }, givewell: "top", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 15, founded: 2013, hq: "Washington, DC", website: "https://evidenceaction.org/dispensers", tagline: "Chlorine dispensers at water sources for safe drinking water", impactMetric: "$1.50 per person per year", beneficiaries: "4M+ people served" },
  { slug: "brac", name: "BRAC", sector: "Poverty", scores: { impactOutcomes: 93, transparency: 90, dollarEfficiency: 91, evidenceQuality: 92, cloakScore: 87, beneficiaryVoice: 94, adaptability: 95 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 800, founded: 1972, hq: "Dhaka, Bangladesh", website: "https://brac.net", tagline: "The world's largest NGO, empowering people to overcome poverty", impactMetric: "100M+ people reached/yr", beneficiaries: "11 countries" },
  { slug: "one-acre-fund", name: "One Acre Fund", sector: "Agriculture", scores: { impactOutcomes: 92, transparency: 93, dollarEfficiency: 90, evidenceQuality: 91, cloakScore: 92, beneficiaryVoice: 93, adaptability: 91 }, givewell: "standout", cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 95, founded: 2006, hq: "Nairobi, Kenya", website: "https://oneacrefund.org", tagline: "Supplying smallholder farmers with financing and training", impactMetric: "50% average income increase", beneficiaries: "1.5M farmers served" },
  { slug: "village-enterprise", name: "Village Enterprise", sector: "Poverty", scores: { impactOutcomes: 90, transparency: 89, dollarEfficiency: 91, evidenceQuality: 90, cloakScore: 88, beneficiaryVoice: 92, adaptability: 89 }, givewell: "standout", cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 12, founded: 1987, hq: "San Carlos, USA", website: "https://villageenterprise.org", tagline: "Ending extreme poverty through entrepreneurship and innovation", impactMetric: "$150 per business started", beneficiaries: "250K+ entrepreneurs" },
  { slug: "trickle-up", name: "Trickle Up", sector: "Poverty", scores: { impactOutcomes: 87, transparency: 86, dollarEfficiency: 89, evidenceQuality: 85, cloakScore: 84, beneficiaryVoice: 91, adaptability: 86 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 8, founded: 1979, hq: "New York, USA", website: "https://trickleup.org", tagline: "Graduation approach to lift ultra-poor households out of poverty", impactMetric: "$500 per household graduated", beneficiaries: "500K+ participants" },
  { slug: "save-the-children", name: "Save the Children", sector: "Children", scores: { impactOutcomes: 88, transparency: 90, dollarEfficiency: 84, evidenceQuality: 87, cloakScore: 83, beneficiaryVoice: 86, adaptability: 90 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 2200, founded: 1919, hq: "London, UK", website: "https://savethechildren.org", tagline: "Giving children a healthy start, the opportunity to learn, and protection from harm", impactMetric: "100M+ children reached/yr", beneficiaries: "120 countries" },
  { slug: "unicef-usa", name: "UNICEF USA", sector: "Children", scores: { impactOutcomes: 87, transparency: 89, dollarEfficiency: 83, evidenceQuality: 88, cloakScore: 82, beneficiaryVoice: 84, adaptability: 89 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 700, founded: 1947, hq: "New York, USA", website: "https://unicefusa.org", tagline: "Working in 190 countries for every child, everywhere", impactMetric: "3B vaccine doses/yr", beneficiaries: "190 countries" },
  { slug: "action-against-hunger", name: "Action Against Hunger", sector: "Nutrition", scores: { impactOutcomes: 89, transparency: 90, dollarEfficiency: 86, evidenceQuality: 87, cloakScore: 88, beneficiaryVoice: 87, adaptability: 88 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 500, founded: 1979, hq: "New York, USA", website: "https://actionagainsthunger.org", tagline: "Ending world hunger through treating and preventing malnutrition", impactMetric: "28M people reached/yr", beneficiaries: "50+ countries" },
  { slug: "feeding-america", name: "Feeding America", sector: "Nutrition", scores: { impactOutcomes: 86, transparency: 92, dollarEfficiency: 90, evidenceQuality: 80, cloakScore: 85, beneficiaryVoice: 82, adaptability: 84 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 3500, founded: 1979, hq: "Chicago, USA", website: "https://feedingamerica.org", tagline: "The nation's largest domestic hunger-relief organization", impactMetric: "5.3B meals/yr", beneficiaries: "40M Americans" },
  { slug: "the-humane-league", name: "The Humane League", sector: "Animals", scores: { impactOutcomes: 91, transparency: 90, dollarEfficiency: 93, evidenceQuality: 88, cloakScore: 91, beneficiaryVoice: 75, adaptability: 90 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 15, founded: 2005, hq: "Bethesda, USA", website: "https://thehumaneleague.org", tagline: "Ending the abuse of animals raised for food through corporate campaigns", impactMetric: "100+ corporate pledges won", beneficiaries: "Billions of animals" },
  { slug: "animal-equality", name: "Animal Equality", sector: "Animals", scores: { impactOutcomes: 89, transparency: 88, dollarEfficiency: 91, evidenceQuality: 84, cloakScore: 89, beneficiaryVoice: 73, adaptability: 88 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 10, founded: 2006, hq: "Los Angeles, USA", website: "https://animalequality.org", tagline: "Investigating and exposing animal cruelty through undercover work", impactMetric: "200+ investigations", beneficiaries: "8 countries" },
  { slug: "good-food-institute", name: "Good Food Institute", sector: "Animals", scores: { impactOutcomes: 88, transparency: 89, dollarEfficiency: 87, evidenceQuality: 86, cloakScore: 90, beneficiaryVoice: 70, adaptability: 92 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 25, founded: 2016, hq: "Washington, DC", website: "https://gfi.org", tagline: "Accelerating alternative proteins to transform the food system", impactMetric: "$3B+ invested in alt protein", beneficiaries: "Global food system" },
  { slug: "strongminds", name: "StrongMinds", sector: "Mental Health", scores: { impactOutcomes: 92, transparency: 91, dollarEfficiency: 94, evidenceQuality: 90, cloakScore: 92, beneficiaryVoice: 93, adaptability: 89 }, givewell: "standout", cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 10, founded: 2013, hq: "New York, USA", website: "https://strongminds.org", tagline: "Group interpersonal therapy for depression in Africa", impactMetric: "$170 per DALY averted", beneficiaries: "300K+ women treated" },
  { slug: "basic-needs", name: "BasicNeeds", sector: "Mental Health", scores: { impactOutcomes: 84, transparency: 83, dollarEfficiency: 86, evidenceQuality: 82, cloakScore: 81, beneficiaryVoice: 88, adaptability: 83 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 2000, hq: "Leamington Spa, UK", website: "https://basicneeds.org", tagline: "Mental health and development in low-income countries", impactMetric: "$50 per person treated", beneficiaries: "1M+ people reached" },
  { slug: "human-rights-watch", name: "Human Rights Watch", sector: "Human Rights", scores: { impactOutcomes: 85, transparency: 91, dollarEfficiency: 80, evidenceQuality: 93, cloakScore: 89, beneficiaryVoice: 82, adaptability: 87 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 100, founded: 1978, hq: "New York, USA", website: "https://hrw.org", tagline: "Investigating and reporting on abuses happening in all corners of the world", impactMetric: "100+ reports/yr", beneficiaries: "90+ countries" },
  { slug: "aclu", name: "American Civil Liberties Union", sector: "Human Rights", scores: { impactOutcomes: 83, transparency: 88, dollarEfficiency: 78, evidenceQuality: 85, cloakScore: 84, beneficiaryVoice: 80, adaptability: 86 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 350, founded: 1920, hq: "New York, USA", website: "https://aclu.org", tagline: "Defending and preserving individual rights and liberties", impactMetric: "2,000+ court cases/yr", beneficiaries: "All Americans" },
  { slug: "americares", name: "Americares", sector: "Disaster Relief", scores: { impactOutcomes: 89, transparency: 92, dollarEfficiency: 94, evidenceQuality: 84, cloakScore: 88, beneficiaryVoice: 83, adaptability: 90 }, givewell: null, cnStars: 4, charityWatch: "A+", candidSeal: "platinum", donationsM: 900, founded: 1982, hq: "Stamford, USA", website: "https://americares.org", tagline: "Health-focused relief and development organization", impactMetric: "$1B+ in aid delivered/yr", beneficiaries: "90+ countries" },
  { slug: "all-hands-and-hearts", name: "All Hands and Hearts", sector: "Disaster Relief", scores: { impactOutcomes: 87, transparency: 89, dollarEfficiency: 88, evidenceQuality: 81, cloakScore: 90, beneficiaryVoice: 91, adaptability: 89 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 20, founded: 2005, hq: "Mattapoisett, USA", website: "https://allhandsandhearts.org", tagline: "Volunteer-powered disaster relief and rebuilding", impactMetric: "500+ projects completed", beneficiaries: "30+ countries" },
  { slug: "evidence-action-iron", name: "Iron Fortification (Evidence Action)", sector: "Nutrition", scores: { impactOutcomes: 90, transparency: 91, dollarEfficiency: 93, evidenceQuality: 88, cloakScore: 90, beneficiaryVoice: 82, adaptability: 87 }, givewell: "standout", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 8, founded: 2013, hq: "Washington, DC", website: "https://evidenceaction.org", tagline: "Large-scale iron and folic acid fortification of staple foods", impactMetric: "$0.15 per person per year", beneficiaries: "50M+ people reached" },
  { slug: "deworm-the-world", name: "Deworm the World Initiative", sector: "Global Health", scores: { impactOutcomes: 95, transparency: 93, dollarEfficiency: 97, evidenceQuality: 93, cloakScore: 92, beneficiaryVoice: 85, adaptability: 90 }, givewell: "top", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 20, founded: 2007, hq: "Washington, DC", website: "https://evidenceaction.org/deworm-the-world", tagline: "Government-led school-based deworming programs", impactMetric: "$0.05 per child dewormed", beneficiaries: "280M+ children/yr" },
  { slug: "population-services-international", name: "Population Services International (PSI)", sector: "Global Health", scores: { impactOutcomes: 90, transparency: 88, dollarEfficiency: 87, evidenceQuality: 89, cloakScore: 85, beneficiaryVoice: 86, adaptability: 91 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 600, founded: 1970, hq: "Washington, DC", website: "https://psi.org", tagline: "Making it easier for people in the developing world to be healthy", impactMetric: "500M+ health products/yr", beneficiaries: "50+ countries" },
  { slug: "fred-hollows-foundation", name: "Fred Hollows Foundation", sector: "Global Health", scores: { impactOutcomes: 91, transparency: 90, dollarEfficiency: 92, evidenceQuality: 87, cloakScore: 89, beneficiaryVoice: 88, adaptability: 86 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 100, founded: 1992, hq: "Sydney, Australia", website: "https://hollows.org", tagline: "Ending avoidable blindness in developing countries", impactMetric: "$25 per cataract surgery", beneficiaries: "3M+ surgeries" },
  { slug: "project-healthy-children", name: "Project Healthy Children", sector: "Nutrition", scores: { impactOutcomes: 89, transparency: 87, dollarEfficiency: 94, evidenceQuality: 85, cloakScore: 88, beneficiaryVoice: 79, adaptability: 84 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 3, founded: 2002, hq: "Cambridge, USA", website: "https://projecthealthychildren.org", tagline: "National food fortification programs in developing countries", impactMetric: "$0.08 per person per year", beneficiaries: "100M+ people reached" },
  { slug: "possible", name: "Possible", sector: "Global Health", scores: { impactOutcomes: 88, transparency: 86, dollarEfficiency: 88, evidenceQuality: 87, cloakScore: 87, beneficiaryVoice: 92, adaptability: 88 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 6, founded: 2008, hq: "New York, USA", website: "https://possiblehealth.org", tagline: "High-quality healthcare delivery in rural Nepal", impactMetric: "$30 per patient per year", beneficiaries: "300K+ patients/yr" },
  { slug: "living-goods", name: "Living Goods", sector: "Global Health", scores: { impactOutcomes: 91, transparency: 89, dollarEfficiency: 90, evidenceQuality: 90, cloakScore: 88, beneficiaryVoice: 90, adaptability: 89 }, givewell: "standout", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 25, founded: 2007, hq: "Kampala, Uganda", website: "https://livinggoods.org", tagline: "Community health workers delivering door-to-door care", impactMetric: "27% child mortality reduction", beneficiaries: "35M+ people served" },
  { slug: "carbon180", name: "Carbon180", sector: "Environment", scores: { impactOutcomes: 85, transparency: 87, dollarEfficiency: 86, evidenceQuality: 88, cloakScore: 89, beneficiaryVoice: 70, adaptability: 90 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 2015, hq: "Washington, DC", website: "https://carbon180.org", tagline: "Policy advocacy for carbon removal solutions", impactMetric: "Key policy wins for CDR", beneficiaries: "Global climate" },
  { slug: "world-wildlife-fund", name: "World Wildlife Fund", sector: "Environment", scores: { impactOutcomes: 82, transparency: 86, dollarEfficiency: 78, evidenceQuality: 83, cloakScore: 76, beneficiaryVoice: 75, adaptability: 85 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 350, founded: 1961, hq: "Gland, Switzerland", website: "https://worldwildlife.org", tagline: "Building a future in which people live in harmony with nature", impactMetric: "Protecting 1.4B acres", beneficiaries: "100+ countries" },
  { slug: "conservation-international", name: "Conservation International", sector: "Environment", scores: { impactOutcomes: 84, transparency: 87, dollarEfficiency: 80, evidenceQuality: 84, cloakScore: 79, beneficiaryVoice: 77, adaptability: 86 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 200, founded: 1987, hq: "Arlington, USA", website: "https://conservation.org", tagline: "Protecting nature for the benefit of humanity", impactMetric: "600M hectares protected", beneficiaries: "30+ countries" },
  { slug: "earthjustice", name: "Earthjustice", sector: "Environment", scores: { impactOutcomes: 86, transparency: 90, dollarEfficiency: 85, evidenceQuality: 86, cloakScore: 91, beneficiaryVoice: 78, adaptability: 84 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 150, founded: 1971, hq: "San Francisco, USA", website: "https://earthjustice.org", tagline: "The premier nonprofit environmental law organization", impactMetric: "1,000+ cases litigated", beneficiaries: "All Americans" },
  { slug: "camfed", name: "CAMFED", sector: "Education", scores: { impactOutcomes: 91, transparency: 90, dollarEfficiency: 91, evidenceQuality: 88, cloakScore: 89, beneficiaryVoice: 94, adaptability: 90 }, givewell: "standout", cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 40, founded: 1993, hq: "Cambridge, UK", website: "https://camfed.org", tagline: "Girls' education and women's empowerment in sub-Saharan Africa", impactMetric: "6.8M+ students supported", beneficiaries: "5 countries" },
  { slug: "pencils-of-promise", name: "Pencils of Promise", sector: "Education", scores: { impactOutcomes: 83, transparency: 86, dollarEfficiency: 82, evidenceQuality: 79, cloakScore: 85, beneficiaryVoice: 84, adaptability: 82 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "gold", donationsM: 15, founded: 2008, hq: "New York, USA", website: "https://pencilsofpromise.org", tagline: "Building schools and increasing educational opportunities", impactMetric: "550+ schools built", beneficiaries: "200K+ students" },
  { slug: "educate-girls", name: "Educate Girls", sector: "Education", scores: { impactOutcomes: 90, transparency: 88, dollarEfficiency: 92, evidenceQuality: 89, cloakScore: 87, beneficiaryVoice: 91, adaptability: 88 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 8, founded: 2007, hq: "Mumbai, India", website: "https://educategirls.ngo", tagline: "Mobilizing communities for girls' education in India", impactMetric: "1.4M+ girls enrolled", beneficiaries: "21K+ villages" },
  { slug: "kiva", name: "Kiva", sector: "Poverty", scores: { impactOutcomes: 82, transparency: 90, dollarEfficiency: 80, evidenceQuality: 78, cloakScore: 88, beneficiaryVoice: 85, adaptability: 86 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 200, founded: 2005, hq: "San Francisco, USA", website: "https://kiva.org", tagline: "Crowdfunded microloans to underserved communities worldwide", impactMetric: "$2B+ loans funded", beneficiaries: "4M+ borrowers" },
  { slug: "heifer-international", name: "Heifer International", sector: "Agriculture", scores: { impactOutcomes: 81, transparency: 85, dollarEfficiency: 78, evidenceQuality: 77, cloakScore: 80, beneficiaryVoice: 83, adaptability: 82 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 200, founded: 1944, hq: "Little Rock, USA", website: "https://heifer.org", tagline: "Ending hunger and poverty through sustainable agriculture", impactMetric: "37M families helped", beneficiaries: "21 countries" },
  { slug: "opportunity-international", name: "Opportunity International", sector: "Poverty", scores: { impactOutcomes: 84, transparency: 86, dollarEfficiency: 83, evidenceQuality: 80, cloakScore: 82, beneficiaryVoice: 85, adaptability: 84 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "gold", donationsM: 50, founded: 1971, hq: "Chicago, USA", website: "https://opportunity.org", tagline: "Microfinance and training for entrepreneurs in developing countries", impactMetric: "18M+ clients served", beneficiaries: "20+ countries" },
  { slug: "idinsight", name: "IDinsight", sector: "Global Dev", scores: { impactOutcomes: 88, transparency: 90, dollarEfficiency: 87, evidenceQuality: 96, cloakScore: 93, beneficiaryVoice: 89, adaptability: 91 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 15, founded: 2011, hq: "New Delhi, India", website: "https://idinsight.org", tagline: "Using data and evidence to help leaders combat poverty", impactMetric: "200+ evaluations completed", beneficiaries: "50+ countries" },
  { slug: "habitat-for-humanity", name: "Habitat for Humanity", sector: "Housing", scores: { impactOutcomes: 83, transparency: 88, dollarEfficiency: 79, evidenceQuality: 78, cloakScore: 82, beneficiaryVoice: 86, adaptability: 83 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 1600, founded: 1976, hq: "Atlanta, USA", website: "https://habitat.org", tagline: "Building homes, communities, and hope", impactMetric: "35M+ people served", beneficiaries: "70+ countries" },
  { slug: "innocence-project", name: "Innocence Project", sector: "Criminal Justice", scores: { impactOutcomes: 87, transparency: 89, dollarEfficiency: 84, evidenceQuality: 91, cloakScore: 90, beneficiaryVoice: 88, adaptability: 85 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 25, founded: 1992, hq: "New York, USA", website: "https://innocenceproject.org", tagline: "Exonerating the wrongly convicted through DNA testing", impactMetric: "245+ exonerations", beneficiaries: "Thousands freed" },
  { slug: "acumen", name: "Acumen", sector: "Community Dev", scores: { impactOutcomes: 86, transparency: 87, dollarEfficiency: 83, evidenceQuality: 85, cloakScore: 86, beneficiaryVoice: 88, adaptability: 90 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 30, founded: 2001, hq: "New York, USA", website: "https://acumen.org", tagline: "Investing in companies, leaders, and ideas to change the way the world tackles poverty", impactMetric: "$150M+ invested", beneficiaries: "400M+ lives impacted" },
  { slug: "end-fund", name: "END Fund", sector: "Global Health", scores: { impactOutcomes: 90, transparency: 89, dollarEfficiency: 92, evidenceQuality: 88, cloakScore: 87, beneficiaryVoice: 83, adaptability: 86 }, givewell: "standout", cnStars: null, charityWatch: null, candidSeal: null, donationsM: 30, founded: 2012, hq: "New York, USA", website: "https://end.org", tagline: "Ending neglected tropical diseases through strategic partnerships", impactMetric: "750M+ treatments funded", beneficiaries: "30+ countries" },
  { slug: "iodine-global-network", name: "Iodine Global Network", sector: "Nutrition", scores: { impactOutcomes: 88, transparency: 85, dollarEfficiency: 95, evidenceQuality: 86, cloakScore: 84, beneficiaryVoice: 74, adaptability: 82 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 2, founded: 1986, hq: "Ottawa, Canada", website: "https://ign.org", tagline: "Eliminating iodine deficiency worldwide through salt iodization", impactMetric: "$0.05 per person per year", beneficiaries: "120+ countries" },
  { slug: "clinton-health-access", name: "Clinton Health Access Initiative", sector: "Global Health", scores: { impactOutcomes: 90, transparency: 84, dollarEfficiency: 86, evidenceQuality: 88, cloakScore: 78, beneficiaryVoice: 80, adaptability: 91 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 300, founded: 2002, hq: "Boston, USA", website: "https://clintonhealthaccess.org", tagline: "Saving lives and reducing the burden of disease in low-income countries", impactMetric: "70+ countries supported", beneficiaries: "Billions impacted" },
  { slug: "path", name: "PATH", sector: "Global Health", scores: { impactOutcomes: 89, transparency: 87, dollarEfficiency: 84, evidenceQuality: 90, cloakScore: 85, beneficiaryVoice: 82, adaptability: 90 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 400, founded: 1977, hq: "Seattle, USA", website: "https://path.org", tagline: "Accelerating health equity through innovation and partnerships", impactMetric: "70+ countries", beneficiaries: "Global health systems" },
  { slug: "jhpiego", name: "Jhpiego", sector: "Global Health", scores: { impactOutcomes: 87, transparency: 86, dollarEfficiency: 85, evidenceQuality: 88, cloakScore: 83, beneficiaryVoice: 84, adaptability: 87 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 500, founded: 1973, hq: "Baltimore, USA", website: "https://jhpiego.org", tagline: "Creating and delivering transformative healthcare solutions", impactMetric: "150M+ women & families/yr", beneficiaries: "40+ countries" },
  { slug: "global-fund", name: "The Global Fund", sector: "Global Health", scores: { impactOutcomes: 92, transparency: 90, dollarEfficiency: 85, evidenceQuality: 91, cloakScore: 84, beneficiaryVoice: 81, adaptability: 88 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5000, founded: 2002, hq: "Geneva, Switzerland", website: "https://theglobalfund.org", tagline: "Investing the world's money to defeat HIV, TB, and malaria", impactMetric: "59M lives saved", beneficiaries: "100+ countries" },
  { slug: "gavi", name: "Gavi, the Vaccine Alliance", sector: "Global Health", scores: { impactOutcomes: 93, transparency: 89, dollarEfficiency: 88, evidenceQuality: 92, cloakScore: 86, beneficiaryVoice: 80, adaptability: 90 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 4000, founded: 2000, hq: "Geneva, Switzerland", website: "https://gavi.org", tagline: "Saving lives and protecting health by increasing equitable use of vaccines", impactMetric: "1B+ children vaccinated", beneficiaries: "73 countries" },
  { slug: "wikimedia-foundation", name: "Wikimedia Foundation", sector: "Technology", scores: { impactOutcomes: 84, transparency: 93, dollarEfficiency: 82, evidenceQuality: 80, cloakScore: 95, beneficiaryVoice: 90, adaptability: 88 }, givewell: null, cnStars: 4, charityWatch: "B+", candidSeal: "platinum", donationsM: 180, founded: 2003, hq: "San Francisco, USA", website: "https://wikimediafoundation.org", tagline: "Free knowledge for every single person on the planet", impactMetric: "60M+ articles", beneficiaries: "1.7B users/month" },
  { slug: "internet-archive", name: "Internet Archive", sector: "Technology", scores: { impactOutcomes: 82, transparency: 88, dollarEfficiency: 85, evidenceQuality: 77, cloakScore: 92, beneficiaryVoice: 80, adaptability: 86 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 30, founded: 1996, hq: "San Francisco, USA", website: "https://archive.org", tagline: "Universal access to all knowledge", impactMetric: "835B+ web pages archived", beneficiaries: "Global internet" },
  { slug: "electronic-frontier-foundation", name: "Electronic Frontier Foundation", sector: "Technology", scores: { impactOutcomes: 83, transparency: 89, dollarEfficiency: 81, evidenceQuality: 84, cloakScore: 93, beneficiaryVoice: 79, adaptability: 87 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 25, founded: 1990, hq: "San Francisco, USA", website: "https://eff.org", tagline: "Defending civil liberties in the digital world", impactMetric: "Key digital rights victories", beneficiaries: "Global internet users" },
  { slug: "code-for-america", name: "Code for America", sector: "Technology", scores: { impactOutcomes: 80, transparency: 86, dollarEfficiency: 79, evidenceQuality: 78, cloakScore: 87, beneficiaryVoice: 82, adaptability: 85 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 20, founded: 2009, hq: "San Francisco, USA", website: "https://codeforamerica.org", tagline: "Making government work for the people, by the people, in the digital age", impactMetric: "10M+ people served", beneficiaries: "US government services" },
  { slug: "oxfam", name: "Oxfam International", sector: "Poverty", scores: { impactOutcomes: 84, transparency: 85, dollarEfficiency: 79, evidenceQuality: 83, cloakScore: 77, beneficiaryVoice: 86, adaptability: 87 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 1400, founded: 1942, hq: "Nairobi, Kenya", website: "https://oxfam.org", tagline: "Fighting inequality to end poverty and injustice", impactMetric: "25M+ people reached/yr", beneficiaries: "90+ countries" },
  { slug: "care", name: "CARE International", sector: "Humanitarian", scores: { impactOutcomes: 85, transparency: 87, dollarEfficiency: 81, evidenceQuality: 84, cloakScore: 80, beneficiaryVoice: 87, adaptability: 86 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 800, founded: 1945, hq: "Geneva, Switzerland", website: "https://care-international.org", tagline: "Fighting global poverty with a focus on women and girls", impactMetric: "100M+ people/yr", beneficiaries: "100+ countries" },
  { slug: "mercy-corps", name: "Mercy Corps", sector: "Humanitarian", scores: { impactOutcomes: 86, transparency: 88, dollarEfficiency: 82, evidenceQuality: 85, cloakScore: 81, beneficiaryVoice: 87, adaptability: 89 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 550, founded: 1979, hq: "Portland, USA", website: "https://mercycorps.org", tagline: "Helping people survive through crisis, build better lives, and transform their communities", impactMetric: "37M+ people reached/yr", beneficiaries: "40+ countries" },
  { slug: "plan-international", name: "Plan International", sector: "Children", scores: { impactOutcomes: 84, transparency: 86, dollarEfficiency: 80, evidenceQuality: 83, cloakScore: 79, beneficiaryVoice: 85, adaptability: 84 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 1000, founded: 1937, hq: "Woking, UK", website: "https://plan-international.org", tagline: "Advancing children's rights and equality for girls", impactMetric: "50M+ children reached/yr", beneficiaries: "75+ countries" },
  { slug: "world-vision", name: "World Vision", sector: "Children", scores: { impactOutcomes: 82, transparency: 84, dollarEfficiency: 78, evidenceQuality: 80, cloakScore: 75, beneficiaryVoice: 83, adaptability: 82 }, givewell: null, cnStars: 3, charityWatch: "B+", candidSeal: "platinum", donationsM: 3000, founded: 1950, hq: "Monrovia, USA", website: "https://worldvision.org", tagline: "Helping the world's most vulnerable children overcome poverty", impactMetric: "200M+ people helped", beneficiaries: "100+ countries" },
  { slug: "international-medical-corps", name: "International Medical Corps", sector: "Humanitarian", scores: { impactOutcomes: 86, transparency: 87, dollarEfficiency: 84, evidenceQuality: 83, cloakScore: 82, beneficiaryVoice: 84, adaptability: 88 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 500, founded: 1984, hq: "Los Angeles, USA", website: "https://internationalmedicalcorps.org", tagline: "Helping those in need, anywhere, at any time", impactMetric: "Millions treated/yr", beneficiaries: "30+ countries" },
  { slug: "wateraid", name: "WaterAid", sector: "Water & Sanitation", scores: { impactOutcomes: 87, transparency: 89, dollarEfficiency: 84, evidenceQuality: 85, cloakScore: 86, beneficiaryVoice: 88, adaptability: 85 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 120, founded: 1981, hq: "London, UK", website: "https://wateraid.org", tagline: "Clean water, decent toilets, and good hygiene for everyone, everywhere", impactMetric: "26M+ people reached", beneficiaries: "34 countries" },
  { slug: "global-giving", name: "GlobalGiving", sector: "Community Dev", scores: { impactOutcomes: 79, transparency: 91, dollarEfficiency: 80, evidenceQuality: 76, cloakScore: 90, beneficiaryVoice: 84, adaptability: 85 }, givewell: null, cnStars: 4, charityWatch: null, candidSeal: "platinum", donationsM: 80, founded: 2002, hq: "Washington, DC", website: "https://globalgiving.org", tagline: "Connecting nonprofits, donors, and companies in nearly every country", impactMetric: "$800M+ raised", beneficiaries: "30K+ projects" },
  { slug: "ashoka", name: "Ashoka", sector: "Community Dev", scores: { impactOutcomes: 81, transparency: 84, dollarEfficiency: 78, evidenceQuality: 79, cloakScore: 83, beneficiaryVoice: 82, adaptability: 90 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 40, founded: 1980, hq: "Arlington, USA", website: "https://ashoka.org", tagline: "Everyone a changemaker — the world's largest network of social entrepreneurs", impactMetric: "3,800+ fellows", beneficiaries: "90+ countries" },
  { slug: "skoll-foundation", name: "Skoll Foundation", sector: "Community Dev", scores: { impactOutcomes: 83, transparency: 85, dollarEfficiency: 79, evidenceQuality: 81, cloakScore: 84, beneficiaryVoice: 80, adaptability: 88 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 50, founded: 1999, hq: "Palo Alto, USA", website: "https://skoll.org", tagline: "Investing in, connecting, and celebrating social entrepreneurs", impactMetric: "$600M+ invested", beneficiaries: "5 continents" },
  { slug: "results", name: "RESULTS", sector: "Poverty", scores: { impactOutcomes: 80, transparency: 83, dollarEfficiency: 82, evidenceQuality: 81, cloakScore: 84, beneficiaryVoice: 79, adaptability: 83 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 5, founded: 1980, hq: "Washington, DC", website: "https://results.org", tagline: "Grassroots advocacy to end poverty", impactMetric: "Key policy wins", beneficiaries: "US & global" },
  { slug: "the-carter-center", name: "The Carter Center", sector: "Global Health", scores: { impactOutcomes: 88, transparency: 89, dollarEfficiency: 85, evidenceQuality: 87, cloakScore: 86, beneficiaryVoice: 83, adaptability: 86 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 100, founded: 1982, hq: "Atlanta, USA", website: "https://cartercenter.org", tagline: "Waging peace, fighting disease, building hope", impactMetric: "Near-eradication of Guinea worm", beneficiaries: "80+ countries" },
  { slug: "cure-violence", name: "Cure Violence Global", sector: "Criminal Justice", scores: { impactOutcomes: 85, transparency: 84, dollarEfficiency: 83, evidenceQuality: 86, cloakScore: 83, beneficiaryVoice: 87, adaptability: 84 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 15, founded: 2000, hq: "Chicago, USA", website: "https://cvg.org", tagline: "Treating violence as a health issue using disease control methods", impactMetric: "40-70% violence reduction", beneficiaries: "30+ cities" },
  { slug: "last-mile-health", name: "Last Mile Health", sector: "Global Health", scores: { impactOutcomes: 89, transparency: 87, dollarEfficiency: 88, evidenceQuality: 87, cloakScore: 86, beneficiaryVoice: 91, adaptability: 88 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 15, founded: 2007, hq: "Boston, USA", website: "https://lastmilehealth.org", tagline: "Community health workers reaching the most remote communities", impactMetric: "3,000+ CHWs deployed", beneficiaries: "1.2M+ people served" },
  { slug: "mothers2mothers", name: "mothers2mothers", sector: "Global Health", scores: { impactOutcomes: 90, transparency: 88, dollarEfficiency: 87, evidenceQuality: 86, cloakScore: 87, beneficiaryVoice: 94, adaptability: 87 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 20, founded: 2001, hq: "Cape Town, South Africa", website: "https://m2m.org", tagline: "Employing women living with HIV as community health workers", impactMetric: "Virtual elimination of MTCT", beneficiaries: "10 African countries" },
  { slug: "tostan", name: "Tostan", sector: "Human Rights", scores: { impactOutcomes: 86, transparency: 85, dollarEfficiency: 87, evidenceQuality: 84, cloakScore: 84, beneficiaryVoice: 93, adaptability: 86 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 1991, hq: "Dakar, Senegal", website: "https://tostan.org", tagline: "Community-led development ending FGM and child marriage", impactMetric: "8,800+ communities declared abandonment", beneficiaries: "West Africa" },
  { slug: "landesa", name: "Landesa", sector: "Poverty", scores: { impactOutcomes: 85, transparency: 84, dollarEfficiency: 88, evidenceQuality: 83, cloakScore: 82, beneficiaryVoice: 86, adaptability: 84 }, givewell: null, cnStars: 3, charityWatch: null, candidSeal: "gold", donationsM: 10, founded: 1981, hq: "Seattle, USA", website: "https://landesa.org", tagline: "Securing land rights for the world's poorest people", impactMetric: "180M+ families secured", beneficiaries: "50+ countries" },
  { slug: "sunlight-foundation", name: "Sunlight Foundation (legacy)", sector: "Technology", scores: { impactOutcomes: 78, transparency: 94, dollarEfficiency: 80, evidenceQuality: 79, cloakScore: 96, beneficiaryVoice: 75, adaptability: 80 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 2006, hq: "Washington, DC", website: "https://sunlightfoundation.com", tagline: "Making government more accountable and transparent through technology", impactMetric: "Key open data policies", beneficiaries: "US government" },
  { slug: "center-for-global-development", name: "Center for Global Development", sector: "Global Dev", scores: { impactOutcomes: 84, transparency: 88, dollarEfficiency: 82, evidenceQuality: 94, cloakScore: 90, beneficiaryVoice: 73, adaptability: 86 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 20, founded: 2001, hq: "Washington, DC", website: "https://cgdev.org", tagline: "Independent research and practical ideas for global prosperity", impactMetric: "Key policy influence", beneficiaries: "Global development" },
  { slug: "j-pal", name: "J-PAL (Abdul Latif Jameel Poverty Action Lab)", sector: "Global Dev", scores: { impactOutcomes: 90, transparency: 91, dollarEfficiency: 86, evidenceQuality: 99, cloakScore: 93, beneficiaryVoice: 82, adaptability: 90 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 40, founded: 2003, hq: "Cambridge, USA", website: "https://povertyactionlab.org", tagline: "Reducing poverty by ensuring that policy is informed by scientific evidence", impactMetric: "1,000+ RCTs completed", beneficiaries: "400M+ people reached" },
  { slug: "innovations-for-poverty-action", name: "Innovations for Poverty Action", sector: "Global Dev", scores: { impactOutcomes: 88, transparency: 89, dollarEfficiency: 85, evidenceQuality: 96, cloakScore: 91, beneficiaryVoice: 84, adaptability: 89 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 30, founded: 2002, hq: "New Haven, USA", website: "https://poverty-action.org", tagline: "Discovering and promoting effective solutions to global poverty", impactMetric: "900+ evaluations", beneficiaries: "50+ countries" },
  { slug: "give-india", name: "GiveIndia", sector: "Community Dev", scores: { impactOutcomes: 80, transparency: 86, dollarEfficiency: 82, evidenceQuality: 77, cloakScore: 85, beneficiaryVoice: 83, adaptability: 84 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 100, founded: 2000, hq: "Mumbai, India", website: "https://giveindia.org", tagline: "India's largest giving platform connecting donors to verified nonprofits", impactMetric: "$500M+ raised", beneficiaries: "India" },
  { slug: "the-life-you-can-save", name: "The Life You Can Save", sector: "Global Dev", scores: { impactOutcomes: 87, transparency: 92, dollarEfficiency: 88, evidenceQuality: 89, cloakScore: 93, beneficiaryVoice: 78, adaptability: 85 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 2009, hq: "Melbourne, Australia", website: "https://thelifeyoucansave.org", tagline: "Curating the most effective charities fighting extreme poverty", impactMetric: "Best-in-class recommendations", beneficiaries: "Global" },
  { slug: "charity-science-health", name: "Charity Science Health", sector: "Global Health", scores: { impactOutcomes: 86, transparency: 85, dollarEfficiency: 90, evidenceQuality: 84, cloakScore: 86, beneficiaryVoice: 80, adaptability: 83 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 2, founded: 2016, hq: "India", website: "https://charitysciencehealth.com", tagline: "SMS reminders to increase childhood immunization rates", impactMetric: "$50 per additional child vaccinated", beneficiaries: "India" },
  { slug: "zusha", name: "Zusha!", sector: "Global Dev", scores: { impactOutcomes: 84, transparency: 83, dollarEfficiency: 93, evidenceQuality: 85, cloakScore: 84, beneficiaryVoice: 78, adaptability: 82 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 1, founded: 2013, hq: "Washington, DC", website: "https://zusha.org", tagline: "Reducing road traffic deaths through passenger empowerment stickers", impactMetric: "25% crash reduction", beneficiaries: "East Africa" },
  { slug: "sanku", name: "Sanku (Project Healthy Children)", sector: "Nutrition", scores: { impactOutcomes: 88, transparency: 86, dollarEfficiency: 93, evidenceQuality: 84, cloakScore: 85, beneficiaryVoice: 79, adaptability: 85 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 5, founded: 2009, hq: "Dar es Salaam, Tanzania", website: "https://sanku.com", tagline: "Small-scale flour fortification technology to end malnutrition", impactMetric: "$0.10 per person per year", beneficiaries: "5M+ people reached" },
  { slug: "seva-foundation", name: "Seva Foundation", sector: "Global Health", scores: { impactOutcomes: 87, transparency: 86, dollarEfficiency: 89, evidenceQuality: 83, cloakScore: 85, beneficiaryVoice: 85, adaptability: 84 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "gold", donationsM: 20, founded: 1978, hq: "Berkeley, USA", website: "https://seva.org", tagline: "Preventing blindness and restoring sight in underserved communities", impactMetric: "$50 per sight-restoring surgery", beneficiaries: "5M+ surgeries" },
  { slug: "fistula-foundation", name: "Fistula Foundation", sector: "Global Health", scores: { impactOutcomes: 89, transparency: 90, dollarEfficiency: 91, evidenceQuality: 84, cloakScore: 89, beneficiaryVoice: 90, adaptability: 85 }, givewell: null, cnStars: 4, charityWatch: "A+", candidSeal: "platinum", donationsM: 15, founded: 2000, hq: "San Jose, USA", website: "https://fistulafoundation.org", tagline: "Providing life-transforming fistula repair surgery to women", impactMetric: "$586 per surgery", beneficiaries: "30+ countries" },
  { slug: "operation-smile", name: "Operation Smile", sector: "Global Health", scores: { impactOutcomes: 85, transparency: 88, dollarEfficiency: 83, evidenceQuality: 81, cloakScore: 84, beneficiaryVoice: 86, adaptability: 83 }, givewell: null, cnStars: 4, charityWatch: "A-", candidSeal: "platinum", donationsM: 250, founded: 1982, hq: "Virginia Beach, USA", website: "https://operationsmile.org", tagline: "Providing free cleft lip and palate surgeries worldwide", impactMetric: "$240 per surgery", beneficiaries: "60+ countries" },
  { slug: "smile-train", name: "Smile Train", sector: "Global Health", scores: { impactOutcomes: 86, transparency: 89, dollarEfficiency: 88, evidenceQuality: 82, cloakScore: 86, beneficiaryVoice: 85, adaptability: 84 }, givewell: null, cnStars: 4, charityWatch: "A", candidSeal: "platinum", donationsM: 200, founded: 1999, hq: "New York, USA", website: "https://smiletrain.org", tagline: "Empowering local medical professionals to provide cleft care", impactMetric: "$250 per surgery", beneficiaries: "90+ countries" },
  { slug: "aravind-eye-care", name: "Aravind Eye Care System", sector: "Global Health", scores: { impactOutcomes: 92, transparency: 85, dollarEfficiency: 96, evidenceQuality: 88, cloakScore: 84, beneficiaryVoice: 88, adaptability: 87 }, givewell: null, cnStars: null, charityWatch: null, candidSeal: null, donationsM: 30, founded: 1976, hq: "Madurai, India", website: "https://aravind.org", tagline: "Eliminating needless blindness through high-volume, low-cost eye care", impactMetric: "$25 per cataract surgery", beneficiaries: "7M+ surgeries" },
];

export const CHARITIES: Charity[] = RAW_CHARITIES.map((c) => {
  const totalScore = computeTotal(c.scores);
  return {
    ...c,
    totalScore,
    grade: gradeFromScore(totalScore),
    cloakStatus: cloakFromScore(c.scores.cloakScore),
  };
}).sort((a, b) => b.totalScore - a.totalScore);

export const STATS = {
  avgScore: Math.round((CHARITIES.reduce((s, c) => s + c.totalScore, 0) / CHARITIES.length) * 10) / 10,
  aTierCount: CHARITIES.filter((c) => c.grade.startsWith("A")).length,
  opacityWarnings: CHARITIES.filter((c) => c.cloakStatus === "hazy" || c.cloakStatus === "opaque").length,
  givewellDirectedM: "$397M",
  totalCharities: CHARITIES.length,
};

export const ALL_SECTORS: Sector[] = Array.from(new Set(CHARITIES.map((c) => c.sector))).sort();
