// Ported from legacy client/src/data/blogData.json: the order legacy's
// BlogPost.tsx walks for "Previous" / "Next" under an essay (editorial order,
// not by date; a post in a series walks its series instead, essay-series.ts),
// and the post's original address for "Originally published at". Posts not
// in Sanity are skipped at render time.

export const POST_ORDER: string[] = [
  "energy-is-money-money-is-memory",
  "your-blood-lies-without-your-dna",
  "when-healing-becomes-extraction",
  "five-cups",
  "the-password-is-killing-you",
  "iboga-ibogaine-the-full-paradox",
  "the-bottle-that-quietly-ends-an-entire-civilization",
  "is-that-a-lot-clarisse-abelarde",
  "you-are-the-moat",
  "frqncy-the-bus-that-restores-the-world",
  "akbar-cuisine-restoration-economics",
  "the-restaurant-with-no-menu-prices-ai-ethics-manifesto",
  "california-toll-roads-legalized-scam",
  "the-1000-hour-hold",
  "conscious-capital-partnership-ecosystem",
  "the-clock-keeper-chronicles-part-1",
  "the-peptide-truth-65m-fraud-industry-vs-life-changing-medicine",
  "find-my-ev-paul-scott-wont-let-you-buy-a-gas-car",
  "the-butchers-daughter-the-carbon-toll-and-the-cheese-that-ate-the-planet",
  "restaurants-beware-of-vegans-and-vegans-beware-of-lying-restaurants",
  "love-as-dharma-a-science-based-playbook-for-magnetic-partnership",
  "the-molecule-as-mirror-from-substance-to-service",
  "molecule-as-mirror-1-three-rooms-one-longing",
  "molecule-as-mirror-2-the-old-maps",
  "molecule-as-mirror-3-the-new-cartographers",
  "molecule-as-mirror-4-power-and-relief",
  "molecule-as-mirror-5-escape-and-meaning",
  "molecule-as-mirror-6-the-pause-protocol",
  "molecule-as-mirror-7-the-pathway-to-dharma",
  "molecule-as-mirror-8-resources-and-costs",
  "molecule-as-mirror-9-a-ceremony-story",
  "molecule-as-mirror-10-what-the-pioneers-know",
  "molecule-as-mirror-11-the-doorway",
  "productivity-apps-that-rocked-my-world-in-2024",
  "forever-chemicals-in-my-blood-pfas-and-microplastics",
  "how-to-alienate-a-loyal-vegan",
  "luz-lounge-where-loyalty-goes-to-die-groupon",
  "trap-how-dmn8-gym-became-a-poster-child-for-fitness-fraud",
  "dmn8-the-most-beautiful-crooked-gym-in-the-world",
  "the-decay-of-modern-day-communication",
  "an-ode-to-kusaki-where-plants-become-culinary-masterpieces",
  "innovative-thinking-with-tony-greenberg-scale-up-show",
  "elixir-of-life-device-and-journey",
  "bread-stuck-with-no-customer-service",
  "india-my-virtual-soul-home",
  "powering-purpose-driven-innovation",
  "gratitude-in-action",
  "energy-as-impact",
  "the-decay-of-professional-phone-calls",
  "from-supply-chain-to-the-blockchain-heal",
  "davos-2022-world-economic-forum-here-we-come",
  "forward-health-is-a-sideway-step-at-best",
  "psychedelics-could-become-extractive-capitalism",
  "founders-institute-tony-outsourci",
  "covid-deniers-need-to-take-a-breath",
  "hiding-fees-tips-in-the-transparent-age",
  "mastering-human-and-business-development",
  "6-act-of-speech-speaking-as-a-tool",
  "marc-andreessen-rebuttal-2020",
  "more-ignorance-or-indignance-in-the-wake-of-covid-19",
  "mastering-bd-the-art-of-the-no-that-opens-the-real-door",
  "the-way-of-dao",
  "enterprise-blockchain-can-big-business-co-opt",
  "what-solutions-are-best-built-with-blockchain",
  "a-historical-perspective-on-blockchain",
  "the-ball-and-blockchain-decentralization",
  "thing-price-gouging-price-fixing",
  "business-at-the-speed-of-light-millisecond-worth",
  "only-time-buys-trust",
  "the-tug-of-war-ethical-vs-economic-decisions",
  "would-you-hire-someone-who-led-a-rebellion",
  "fast-growth-companies-likely-to-fall-part-3",
  "so-now-that-we-admit-we-have-a-problem-part-2",
  "it-challenges-buyers-are-ok-are-you-sure-part-1",
  "the-cios-guide-to-smarter-vendor-negotiation",
  "when-valuations-dont-mean-valuable",
  "the-buyers-sellers-honesty-dance-2",
  "the-buyers-and-sellers-honesty-dance-1",
  "human-operating-system",
  "cios-maximize-roi-or-find-new-role-joe-weinman",
  "the-arithmetic-of-relationships",
  "the-ties-that-bind-interpersonal-relationships",
  "grateful-smuggest-sentiment-or-selfish-act",
  "10-magic-questions-for-projects-success-kick-ass",
  "high-hells-demise-of-powerful-femininity",
  "apologize",
  "clear-communication",
  "origen-restaurant",
  "clout-v-klout-differences-and-never-be-the-same",
  "summit-series-weekend-community",
  "my-other-car-is-a-bentley-not-car-to-leaf-alone",
  "amazon-trumps-all-other-suitors-quest-hulu",
  "jumping-through-hoops-with-hulu-will-hollywood-kill-their-offspring-again",
  "profiling-the-public-cloud-buyer",
  "key-cloud-migration-decisions",
  "founders-institute-anti-millennial-funding-guide",
  "a-cynic-predicts-it-and-media-in-2011",
  "the-2011-cynic-measures-his-predictions",
  "transforming-tony-2-books-mountain-life-strife",
  "break-buggy-whip-now-tipping-for-streaming-video",
  "it-services-good-shoe-10-years-later-ramprate",
  "points-pointless-only-wine-expert-matters",
  "eco-vegan-realities-seriesethical-economic",
  "return-on-investment-going-green-going-green-2",
  "detroits-rut-stagnation-signs-services-markets",
  "save-entrepreneurs-big-business-buying-startup-2",
  "triple-bottom-line-of-soul-gregory-markel",
  "boiling-the-human-summit-harvard-kurzweil",
  "surfing-wwc-worldwide-wine-club",
  "google-verizon-walled-garden-plan",
  "greenberg-kurzweil-scientist-foundation-of-trust",
  "building-services-market-transhuman-era",
  "truth-bias-mutually-exclusive",
  "myth-rfp-everything-half-price",
  "trust-tongue-bottle-wine",
  "why-good-service-is-all-about-trust",
  "customer-service-key-to-business-success",
  "wheres-my-flying-car-and-an-efficient-it-market",
  "drbronners-to-pressurecookers-simplify-your-life",
  "productivity-apps-that-rock-my-world-in-2026",
  "heart-protocol-addendum",
];

export const ORIGINAL_URLS: Record<string, string> = {
  "the-bottle-that-quietly-ends-an-entire-civilization": "https://tonygreenberg.com/blog/the-bottle-that-quietly-ends-an-entire-civilization",
  "you-are-the-moat": "https://tonygreenberg.com/blog/you-are-the-moat",
  "find-my-ev-paul-scott-wont-let-you-buy-a-gas-car": "https://tonygreenberg.com/find-my-ev/",
  "productivity-apps-that-rocked-my-world-in-2024": "https://tonygreenberg.com/productivity-apps-that-rocked-my-world-in-2024/",
  "forever-chemicals-in-my-blood-pfas-and-microplastics": "https://tonygreenberg.com/forever-chemicals-in-my-blood-pfas-and-microplastics/",
  "how-to-alienate-a-loyal-vegan": "https://tonygreenberg.com/how-to-alienate-a-loyal-vegan/",
  "luz-lounge-where-loyalty-goes-to-die-groupon": "https://tonygreenberg.com/luz-lounge-where-loyalty-goes-to-die-groupon/",
  "trap-how-dmn8-gym-became-a-poster-child-for-fitness-fraud": "https://tonygreenberg.com/trap-how-dmn8-gym-became-a-poster-child-for-fitness-fraud/",
  "dmn8-the-most-beautiful-crooked-gym-in-the-world": "https://tonygreenberg.com/dmn8-the-most-beautiful-crooked-gym-in-the-world/",
  "the-decay-of-modern-day-communication": "https://tonygreenberg.com/the-decay-of-modern-day-communication/",
  "an-ode-to-kusaki-where-plants-become-culinary-masterpieces": "https://tonygreenberg.com/an-ode-to-kusaki-where-plants-become-culinary-masterpieces/",
  "innovative-thinking-with-tony-greenberg-scale-up-show": "https://tonygreenberg.com/innovative-thinking-with-tony-greenberg-scale-up-show/",
  "elixir-of-life-device-and-journey": "https://tonygreenberg.com/elixir-of-life-device-and-journey/",
  "bread-stuck-with-no-customer-service": "https://tonygreenberg.com/bread-stuck-with-no-customer-service/",
  "india-my-virtual-soul-home": "https://tonygreenberg.com/india-my-virtual-soul-home/",
  "powering-purpose-driven-innovation": "https://tonygreenberg.com/powering-purpose-driven-innovation/",
  "gratitude-in-action": "https://tonygreenberg.com/gratitude-in-action/",
  "energy-as-impact": "https://tonygreenberg.com/energy-as-impact/",
  "the-decay-of-professional-phone-calls": "https://tonygreenberg.com/the-decay-of-professional-phone-calls/",
  "from-supply-chain-to-the-blockchain-heal": "https://tonygreenberg.com/from-supply-chain-to-the-blockchain-heal/",
  "davos-2022-world-economic-forum-here-we-come": "https://tonygreenberg.com/davos-2022-world-economic-forum-here-we-come/",
  "forward-health-is-a-sideway-step-at-best": "https://tonygreenberg.com/forward-health-is-a-sideway-step-at-best/",
  "psychedelics-could-become-extractive-capitalism": "https://tonygreenberg.com/psychedelics-could-become-extractive-capitalism/",
  "founders-institute-tony-outsourci": "https://tonygreenberg.com/founders-institute-tony-outsourci/",
  "covid-deniers-need-to-take-a-breath": "https://tonygreenberg.com/covid-deniers-need-to-take-a-breath/",
  "hiding-fees-tips-in-the-transparent-age": "https://tonygreenberg.com/hiding-fees-tips-in-the-transparent-age/",
  "mastering-human-and-business-development": "https://tonygreenberg.com/mastering-human-and-business-development/",
  "6-act-of-speech-speaking-as-a-tool": "https://tonygreenberg.com/6-act-of-speech-speaking-as-a-tool/",
  "marc-andreessen-rebuttal-2020": "https://tonygreenberg.com/marc-andreessen-rebuttal-2020/",
  "more-ignorance-or-indignance-in-the-wake-of-covid-19": "https://tonygreenberg.com/more-ignorance-or-indignance-in-the-wake-of-covid-19/",
  "mastering-bd-the-art-of-the-no-that-opens-the-real-door": "https://tonygreenberg.com/mastering-bd-the-art-of-the-no-that-opens-the-real-door/",
  "the-way-of-dao": "https://tonygreenberg.com/the-way-of-dao/",
  "enterprise-blockchain-can-big-business-co-opt": "https://tonygreenberg.com/enterprise-blockchain-can-big-business-co-opt/",
  "what-solutions-are-best-built-with-blockchain": "https://tonygreenberg.com/what-solutions-are-best-built-with-blockchain/",
  "a-historical-perspective-on-blockchain": "https://tonygreenberg.com/a-historical-perspective-on-blockchain/",
  "the-ball-and-blockchain-decentralization": "https://tonygreenberg.com/the-ball-and-blockchain-decentralization/",
  "thing-price-gouging-price-fixing": "https://tonygreenberg.com/thing-price-gouging-price-fixing/",
  "business-at-the-speed-of-light-millisecond-worth": "https://tonygreenberg.com/business-at-the-speed-of-light-millisecond-worth/",
  "only-time-buys-trust": "https://tonygreenberg.com/only-time-buys-trust/",
  "the-tug-of-war-ethical-vs-economic-decisions": "https://tonygreenberg.com/the-tug-of-war-ethical-vs-economic-decisions/",
  "would-you-hire-someone-who-led-a-rebellion": "https://tonygreenberg.com/would-you-hire-someone-who-led-a-rebellion/",
  "fast-growth-companies-likely-to-fall-part-3": "https://tonygreenberg.com/fast-growth-companies-likely-to-fall-part-3/",
  "so-now-that-we-admit-we-have-a-problem-part-2": "https://tonygreenberg.com/so-now-that-we-admit-we-have-a-problem-part-2/",
  "it-challenges-buyers-are-ok-are-you-sure-part-1": "https://tonygreenberg.com/it-challenges-buyers-are-ok-are-you-sure-part-1/",
  "the-cios-guide-to-smarter-vendor-negotiation": "https://tonygreenberg.com/the-cios-guide-to-smarter-vendor-negotiation/",
  "when-valuations-dont-mean-valuable": "https://tonygreenberg.com/when-valuations-dont-mean-valuable/",
  "the-buyers-sellers-honesty-dance-2": "https://tonygreenberg.com/the-buyers-sellers-honesty-dance-2/",
  "the-buyers-and-sellers-honesty-dance-1": "https://tonygreenberg.com/the-buyers-and-sellers-honesty-dance-1/",
  "human-operating-system": "https://tonygreenberg.com/human-operating-system/",
  "cios-maximize-roi-or-find-new-role-joe-weinman": "https://tonygreenberg.com/cios-maximize-roi-or-find-new-role-joe-weinman/",
  "the-arithmetic-of-relationships": "https://tonygreenberg.com/the-arithmetic-of-relationships/",
  "the-ties-that-bind-interpersonal-relationships": "https://tonygreenberg.com/the-ties-that-bind-interpersonal-relationships/",
  "grateful-smuggest-sentiment-or-selfish-act": "https://tonygreenberg.com/grateful-smuggest-sentiment-or-selfish-act/",
  "10-magic-questions-for-projects-success-kick-ass": "https://tonygreenberg.com/10-magic-questions-for-projects-success-kick-ass/",
  "high-hells-demise-of-powerful-femininity": "https://tonygreenberg.com/high-hells-demise-of-powerful-femininity/",
  "apologize": "https://tonygreenberg.com/apologize/",
  "clear-communication": "https://tonygreenberg.com/clear-communication/",
  "origen-restaurant": "https://tonygreenberg.com/origen-restaurant/",
  "clout-v-klout-differences-and-never-be-the-same": "https://tonygreenberg.com/clout-v-klout-differences-and-never-be-the-same/",
  "summit-series-weekend-community": "https://tonygreenberg.com/summit-series-weekend-community/",
  "my-other-car-is-a-bentley-not-car-to-leaf-alone": "https://tonygreenberg.com/my-other-car-is-a-bentley-not-car-to-leaf-alone/",
  "amazon-trumps-all-other-suitors-quest-hulu": "https://tonygreenberg.com/amazon-trumps-all-other-suitors-quest-hulu/",
  "jumping-through-hoops-with-hulu-will-hollywood-kill-their-offspring-again": "https://tonygreenberg.com/jumping-through-hoops-with-hulu-will-hollywood-kill-their-offspring-again/",
  "profiling-the-public-cloud-buyer": "https://tonygreenberg.com/profiling-the-public-cloud-buyer/",
  "key-cloud-migration-decisions": "https://tonygreenberg.com/key-cloud-migration-decisions/",
  "founders-institute-anti-millennial-funding-guide": "https://tonygreenberg.com/founders-institute-anti-millennial-funding-guide/",
  "a-cynic-predicts-it-and-media-in-2011": "https://tonygreenberg.com/a-cynic-predicts-it-and-media-in-2011/",
  "the-2011-cynic-measures-his-predictions": "https://tonygreenberg.com/the-2011-cynic-measures-his-predictions/",
  "transforming-tony-2-books-mountain-life-strife": "https://tonygreenberg.com/transforming-tony-2-books-mountain-life-strife/",
  "break-buggy-whip-now-tipping-for-streaming-video": "https://tonygreenberg.com/break-buggy-whip-now-tipping-for-streaming-video/",
  "it-services-good-shoe-10-years-later-ramprate": "https://tonygreenberg.com/it-services-good-shoe-10-years-later-ramprate/",
  "points-pointless-only-wine-expert-matters": "https://tonygreenberg.com/points-pointless-only-wine-expert-matters/",
  "eco-vegan-realities-seriesethical-economic": "https://tonygreenberg.com/eco-vegan-realities-seriesethical-economic/",
  "return-on-investment-going-green-going-green-2": "https://tonygreenberg.com/return-on-investment-going-green-going-green-2/",
  "detroits-rut-stagnation-signs-services-markets": "https://tonygreenberg.com/detroits-rut-stagnation-signs-services-markets/",
  "save-entrepreneurs-big-business-buying-startup-2": "https://tonygreenberg.com/save-entrepreneurs-big-business-buying-startup-2/",
  "triple-bottom-line-of-soul-gregory-markel": "https://tonygreenberg.com/triple-bottom-line-of-soul-gregory-markel/",
  "boiling-the-human-summit-harvard-kurzweil": "https://tonygreenberg.com/boiling-the-human-summit-harvard-kurzweil/",
  "surfing-wwc-worldwide-wine-club": "https://tonygreenberg.com/surfing-wwc-worldwide-wine-club/",
  "google-verizon-walled-garden-plan": "https://tonygreenberg.com/google-verizon-walled-garden-plan/",
  "greenberg-kurzweil-scientist-foundation-of-trust": "https://tonygreenberg.com/greenberg-kurzweil-scientist-foundation-of-trust/",
  "building-services-market-transhuman-era": "https://tonygreenberg.com/building-services-market-transhuman-era/",
  "truth-bias-mutually-exclusive": "https://tonygreenberg.com/truth-bias-mutually-exclusive/",
  "myth-rfp-everything-half-price": "https://tonygreenberg.com/myth-rfp-everything-half-price/",
  "trust-tongue-bottle-wine": "https://tonygreenberg.com/trust-tongue-bottle-wine/",
  "why-good-service-is-all-about-trust": "https://tonygreenberg.com/why-good-service-is-all-about-trust/",
  "customer-service-key-to-business-success": "https://tonygreenberg.com/customer-service-key-to-business-success/",
  "wheres-my-flying-car-and-an-efficient-it-market": "https://tonygreenberg.com/wheres-my-flying-car-and-an-efficient-it-market/",
  "drbronners-to-pressurecookers-simplify-your-life": "https://tonygreenberg.com/drbronners-to-pressurecookers-simplify-your-life/",
};
