import type { PageItem } from "@/lib/search-engine";

/**
 * The site's static search directory — every real page on the site, ported
 * from the legacy Vite/Express app's `SearchPalette.tsx` (855 lines), which
 * holds the current, authoritative ~121-entry inline `PAGES` array used by
 * the live command-palette search. A second, older ~121-entry copy exists at
 * `_legacy-manus-app/client/src/data/searchablePages.ts` — grep-confirmed
 * dead (nothing in the legacy app imports it anymore; `SearchPalette.tsx`
 * itself defines its own inline `PAGES`), so it was NOT used as the source
 * here despite being nearly identical.
 *
 * Every internal `href` below was cross-checked against this app's real
 * routes (`find src/app -maxdepth 1|2 -type d`) and fixed where legacy's
 * link was stale. Real fixes made:
 * - Dharma Finder / Consciousness Scale / Grant Study: legacy links to
 *   `/assessments/*` (an old path this app now only 308-redirects from) —
 *   repointed to the real canonical top-level routes `/dharma-finder`,
 *   `/consciousness-scale`, `/grant-study`.
 * - The Index: `/the-index` isn't a real route (never was, in this app) —
 *   repointed to `/search`, the exact same fix already made twice elsewhere
 *   in this migration (`app/series/page.tsx`, `find-your-me`) for the
 *   identical dead legacy link.
 * - The 5 pre-consolidation Attention Theft sub-pages (Economics, AI Blocker
 *   Finder, Legal Database, The 10 Weapons, Report A Spammer) were never
 *   resurrected as separate routes in this migration (Phase 8: "consolidated
 *   mega-page... the 5 pre-consolidation sub-pages not resurrected") —
 *   repointed to the real in-page section anchors on `/attention-theft`
 *   (`#heresy`, `#blocker-finder`, `#legal`, `#weapons`, `#report`),
 *   confirmed against the real `id="..."` attributes in
 *   `src/app/attention-theft/page.tsx`.
 *
 * Dropped entirely (confirmed 404 on the real app, not on Phase 4/8/10's
 * "explicitly deferred" list as an intentional gap either — genuine,
 * undocumented gaps rather than something to silently 404 from search):
 * - FauxTony (`/fauxtony`) — Phase 10 (FauxTony Chatbot) is entirely
 *   unbuilt: no route handler, no chat widget, nothing under `src/app`.
 * - The Open Door (`/the-open-door`, legacy's `ThoughtCloud.tsx`) — never
 *   ported, no route exists.
 * - I Believed Alex Azzi for $137,000 (`/alex-azzi`) — never ported, no
 *   route exists.
 * - Spamtoast (`/youve-been-reported`) — explicitly deferred per
 *   `NEXTJS-MIGRATION-TODO.md`'s "Explicitly deferred" list ("Spam-tracking
 *   system (`/youve-been-reported`, `/spamtoast`, admin spam tooling)").
 *
 * Kept as real external links (verified live via curl at time of writing,
 * same "real sibling product" trust this migration already extends to
 * external `*.manus.space` tools elsewhere, e.g. `journey-tracker.tsx`):
 * Find My Stem Cells, Find Your Love, Sake Guide.
 *
 * Legacy's per-item emoji `icon` field was dropped rather than ported or
 * mapped 1:1 to lucide-react icons — with 117 distinct emoji glyphs across
 * this list, a faithful per-item lucide mapping would be ~117 individual
 * judgment calls for a compact result-list glyph, not proportionate to the
 * UI (the legacy palette's own "Essays"/blog section already used a single
 * generic icon for every result, no per-item icon). The modal renders one
 * generic icon per section instead, consistent with the "decoration not
 * worth the cost" calls made elsewhere in this migration and this repo's
 * house rule against introducing emoji into written files.
 */
export const SEARCH_DIRECTORY: PageItem[] = [
  { title: "Blog", href: "/", description: "92 essays spanning 15 years of enterprise tech, impact, and consciousness", tags: ["blog", "essays", "writing", "articles"] },
  { title: "Start Here", href: "/start-here", description: "The five essays that tell you who Tony is and what he's about", tags: ["start", "begin", "intro", "first"] },
  { title: "About", href: "/about", description: "The full story — from enterprise tech to psychedelic medicine", tags: ["about", "bio", "biography", "tony"] },
  { title: "The Letter", href: "/the-letter", description: "I have something to show you — the seven doors", tags: ["letter", "home", "doors", "seven"] },
  { title: "Walk Through", href: "/walk-through", description: "Step inside each of the seven doors", tags: ["walk", "doors", "explore", "tour"] },
  { title: "The Territory", href: "/the-territory", description: "The map of everything — heroes, influences, and the landscape", tags: ["territory", "map", "heroes", "influences"] },
  { title: "Engine Room", href: "/engine-room", description: "The portfolio — every company, every thesis, every bet", tags: ["engine", "portfolio", "companies", "investments"] },
  { title: "Under NDA", href: "/under-nda", description: "What happens behind closed doors", tags: ["nda", "confidential", "private", "deals"] },
  { title: "The Body", href: "/the-body", description: "Health, biohacking, and the vessel that carries everything", tags: ["body", "health", "biohacking", "wellness"] },
  { title: "The Nightstand", href: "/the-nightstand", description: "Books that shaped the thinking", tags: ["books", "reading", "nightstand", "library"] },
  { title: "The Web", href: "/the-web", description: "The network of relationships and collaborations", tags: ["web", "network", "connections", "relationships"] },
  { title: "Pick Up the Phone", href: "/pick-up-the-phone", description: "The lost art of the phone call — and how to reach Tony", tags: ["phone", "contact", "call", "reach"] },
  { title: "Journeys", href: "/journeys", description: "Travel, psychedelic experiences, and consciousness exploration", tags: ["journeys", "travel", "psychedelic", "consciousness"] },
  { title: "Built by Tony G", href: "/recent-creations", description: "Things Tony has built recently", tags: ["built", "creations", "portfolio", "projects", "tony g"] },
  { title: "Intel", href: "/intel", description: "Deep dives into portfolio companies and competitive landscapes", tags: ["intel", "research", "analysis", "companies"] },
  { title: "The Index", href: "/search", description: "Every page, every section, every door — the complete map", tags: ["index", "sitemap", "all pages", "directory"] },
  { title: "Ecosystem", href: "/ecosystem", description: "Join the ecosystem — from Spark to Builder to Amplifier", tags: ["ecosystem", "join", "subscribe", "community"] },
  { title: "Published", href: "/published", description: "Books, articles, and published works", tags: ["published", "books", "articles", "writing"] },
  { title: "The Rolodex", href: "/clients", description: "25 years of clients — Microsoft, Disney, Goldman Sachs, Nike", tags: ["clients", "rolodex", "companies", "customers"] },
  { title: "Series", href: "/series", description: "Multi-part essay series on specific topics", tags: ["series", "multi-part", "deep dive"] },
  { title: "Framework", href: "/framework", description: "How I'd Approach Your Problem — the 5-step framework", tags: ["framework", "template", "approach", "methodology"] },
  { title: "Assessments", href: "/assessments", description: "Three research-backed tools: Dharma Finder, Consciousness Scale, Grant Study", tags: ["assessments", "quiz", "dharma", "consciousness", "grant study", "purpose", "test"] },
  { title: "Dharma Finder", href: "/dharma-finder", description: "25 questions to discover your purpose — based on Schmachtenberger's inquiry", tags: ["dharma", "purpose", "schmachtenberger", "quiz", "assessment", "meaning", "service"] },
  { title: "Consciousness Scale", href: "/consciousness-scale", description: "Map your consciousness level on Hawkins' calibrated scale", tags: ["consciousness", "hawkins", "awareness", "enlightenment", "scale", "level", "spiritual"] },
  { title: "Grant Study Assessment", href: "/grant-study", description: "Measure life satisfaction across 5 factors from Harvard's 85-year study", tags: ["grant study", "harvard", "happiness", "satisfaction", "relationships", "wellbeing"] },
  { title: "Find My", href: "/find-my", description: "All assessments in one place — Find What's Yours", tags: ["find my", "assessments", "hub", "discover", "quiz"] },
  { title: "Find Your Peptide", href: "/find-your-peptide", description: "The Peptide Clarity Index™ — 7-axis clinical assessment with 16 archetypes", tags: ["peptide", "bpc-157", "semaglutide", "health", "biohacking", "assessment"] },
  { title: "Find My Stem Cells", href: "https://findmystem-s3lknc4h.manus.space/", description: "Global stem-cell clinic decision engine — assessment, ranked preview, pricing by country, Wall of Shame, and BBNBC scoring", tags: ["stem cells", "stem cell", "regenerative medicine", "cell therapy", "mesenchymal", "msc", "exosomes", "clinic", "clinic ranking", "pricing", "country pricing", "assessment", "bbnbc", "wall of shame"], external: true },
  { title: "Peptide Hall of Shame", href: "/peptide-hall-of-shame", description: "20 US peptide providers audited on 6 clinical criteria — average score 95/100 (worst)", tags: ["peptide", "hall of shame", "audit", "clinic", "questionnaire", "ranking"] },
  { title: "Where Does Your Peptide Dollar Go?", href: "/peptide-supply-chain", description: "Supply chain transparency — see where your money goes: manufacturing, marketing, or profit", tags: ["peptide", "supply chain", "cost", "dollar", "transparency", "credibility"] },
  { title: "Peptide Review-Evidence Matrix", href: "/peptide-matrix", description: "Interactive scatter plot: 5-star reviews ≠ FDA-approved efficacy. See where every entity falls.", tags: ["peptide", "matrix", "reviews", "evidence", "danger zone", "scatter plot", "FDA"] },
  { title: "Peptide Literacy Quiz (25 Questions)", href: "/quiz_25q", description: "Test your peptide knowledge across 5 dimensions: Science Literacy, Red Flag Detection, Provider Evaluation, Regulatory Awareness, Personal Risk.", tags: ["peptide", "quiz", "25 questions", "literacy", "test", "assessment", "red flag", "FDA", "science"] },
  { title: "Find Your Sexuality", href: "/find-your-sexuality", description: "A thoughtful exploration of sexual identity across multiple dimensions", tags: ["sexuality", "identity", "lgbtq", "spectrum", "assessment", "kinsey"] },
  { title: "Find Your Me", href: "/find-your-me", description: "Clarity on identity and direction — values, strengths, and alignment", tags: ["me", "identity", "values", "strengths", "alignment", "purpose", "assessment", "find your"] },
  { title: "Find Your Coffee", href: "/find-your-coffee", description: "Your perfect cup, decoded — 15 questions across 6 dimensions", tags: ["coffee", "espresso", "latte", "brew", "caffeine", "cup", "assessment", "find your"] },
  { title: "Find Your Diet", href: "/find-your-diet", description: "Food philosophy matching — discover your ideal nutritional approach", tags: ["diet", "food", "nutrition", "eating", "vegan", "keto", "paleo", "assessment", "find your"] },
  { title: "Find Your Movement", href: "/find-your-movement", description: "Exercise and fitness style matching — find what moves you", tags: ["movement", "exercise", "fitness", "workout", "gym", "yoga", "running", "assessment", "find your"] },
  { title: "Find Your Sleep", href: "/find-your-sleep", description: "Sleep optimization assessment — unlock better rest", tags: ["sleep", "rest", "insomnia", "circadian", "nap", "assessment", "find your"] },
  { title: "Find Your Therapy", href: "/find-your-therapy", description: "Match with the right therapeutic modality for your needs", tags: ["therapy", "therapist", "mental health", "counseling", "cbt", "psychotherapy", "assessment", "find your"] },
  { title: "Find Your Spirit", href: "/find-your-spirit", description: "Discover your spiritual archetype and path", tags: ["spirit", "spiritual", "meditation", "mindfulness", "archetype", "assessment", "find your"] },
  { title: "Find Your Religion", href: "/find-your-religion", description: "Philosophical and spiritual alignment assessment", tags: ["religion", "faith", "belief", "philosophy", "spiritual", "assessment", "find your"] },
  { title: "Find Your Sake", href: "/find-your-sake", description: "Japanese rice wine preference profile", tags: ["sake", "japanese", "rice wine", "nihonshu", "assessment", "find your"] },
  { title: "Find Your Kitchen", href: "/find-your-kitchen", description: "Cooking style assessment — discover your culinary identity", tags: ["kitchen", "cooking", "chef", "culinary", "food", "recipe", "assessment", "find your"] },
  { title: "Find Your Style", href: "/find-your-style", description: "Personal fashion and aesthetic identity assessment", tags: ["style", "fashion", "clothing", "aesthetic", "wardrobe", "assessment", "find your"] },
  { title: "Find Your Attachment Style", href: "/find-your-attachment-style", description: "Attachment theory assessment — understand your relational patterns", tags: ["attachment", "attachment style", "anxious", "avoidant", "secure", "relationships", "assessment", "find your"] },
  { title: "Find Your Love Language", href: "/find-your-love-language", description: "Love language assessment — discover how you give and receive love", tags: ["love language", "love", "relationships", "chapman", "assessment", "find your"] },
  { title: "Find Your Love", href: "https://intimacyassess-tcir3hon.manus.space", description: "Relational alignment framework — compatibility and pattern analysis", tags: ["love", "intimacy", "relationships", "compatibility", "assessment", "find your"], external: true },
  { title: "Find Your Team", href: "/flow-circuit", description: "Collaboration and leadership style assessment", tags: ["team", "collaboration", "leadership", "management", "assessment", "find your"] },
  { title: "SoulScore", href: "/soulscore", description: "Impact verification and scoring — blockchain-verified impact certificates", tags: ["soulscore", "impact", "soul", "score", "verification", "blockchain", "certificate", "esg"] },
  { title: "Charity Scorecard", href: "/charity-scorecard", description: "Evaluate charities across transparency, impact, and efficiency metrics", tags: ["charity", "scorecard", "nonprofit", "donation", "philanthropy", "impact", "evaluation"] },
  { title: "Life Assessment", href: "/life-assessment", description: "Comprehensive life satisfaction assessment across all dimensions", tags: ["life", "assessment", "satisfaction", "mirror", "reflection", "comprehensive"] },
  { title: "Self-Portrait", href: "/self-portrait", description: "Your composite identity map — unified radar chart across all assessments", tags: ["self portrait", "composite", "radar", "identity", "map", "all assessments"] },
  { title: "Sake Guide", href: "https://sakeguide-sqt7xzxp.manus.space/", description: "The definitive guide to sake — history, brewing, tasting, and the soul of Japanese rice wine", tags: ["sake", "japan", "japanese", "rice wine", "brewing", "tasting", "nihonshu", "drink", "alcohol", "guide"], external: true },
  { title: "Supplier Application", href: "/supplier-intake", description: "Apply to become a verified peptide supply partner — short 3-step qualification form, no uploads required", tags: ["vendor", "supplier", "application", "intake", "peptide", "supply", "partner", "apply", "stage 1"] },
  { title: "AI Ethics Manifesto", href: "/blog/the-restaurant-with-no-menu-prices-ai-ethics-manifesto", description: "Zuck: Fix This Now — $1,520 refund demand, Meta's $10B+ liability rap sheet, and a blueprint for ethical AI billing", tags: ["ai", "ethics", "billing", "manus", "meta", "zuckerberg", "pricing", "credits", "fairness", "living-declaration", "ftc", "refund"] },
  // BrewSoul Coffee Intelligence
  { title: "BrewSoul", href: "/brewsoul", description: "Coffee intelligence platform — 103 coffees scored, 100 chains ranked, 6 identity archetypes", tags: ["brewsoul", "coffee", "espresso", "beans", "roast", "brew", "caffeine", "latte", "cappuccino", "pour over"] },
  { title: "Chain Rankings", href: "/brewsoul/chains", description: "100 coffee chains ranked S through F tier — Starbucks, Blue Bottle, Intelligentsia, and more", tags: ["chain", "starbucks", "dunkin", "blue bottle", "intelligentsia", "peets", "counter culture", "ranking", "coffee chain"] },
  { title: "Coffee Prescription", href: "/brewsoul/prescription", description: "AI-powered coffee recommendations matched to your BrewSoul identity", tags: ["prescription", "recommend", "coffee recommendation", "what coffee", "best coffee", "suggest"] },
  { title: "Browse Coffees", href: "/brewsoul/browse", description: "All 103 coffees with cupping scores, flavor profiles, and QPR ratings", tags: ["browse", "catalog", "coffees", "cupping", "score", "rating"] },
  { title: "Wall of Shame (Coffee)", href: "/brewsoul/wall-of-shame", description: "Coffee fraud, greenwashing, and commodity deception exposed", tags: ["shame", "fraud", "greenwash", "bad coffee", "fake", "commodity"] },
  { title: "Follow The Dollar (Coffee)", href: "/brewsoul/follow-the-dollar", description: "Where your coffee dollar actually goes — supply chain economics", tags: ["dollar", "supply chain", "fair trade", "farmer", "economics", "sourcing", "coffee"] },
  { title: "Coffee Varieties", href: "/brewsoul/varieties", description: "25 coffee varieties with genetics, cup profiles, and rarity", tags: ["variety", "gesha", "bourbon", "typica", "sl28", "caturra", "genetics", "coffee"] },
  { title: "Coffee Processing", href: "/brewsoul/processing", description: "Natural, washed, anaerobic, honey — processing methods explained", tags: ["processing", "natural", "washed", "anaerobic", "honey", "fermentation", "coffee"] },
  { title: "Roaster Directory", href: "/brewsoul/roasters", description: "30+ roasters with transparency scores and sourcing ethics", tags: ["roaster", "roastery", "onyx", "counter culture", "george howell", "tim wendelboe", "coffee"] },
  { title: "Coffee & Health", href: "/brewsoul/health", description: "Coffee and health research — what the science actually says", tags: ["coffee health", "caffeine health", "antioxidant", "cortisol"] },
  { title: "Mold-Free Coffee", href: "/brewsoul/mold-free", description: "Mycotoxin-free coffee guide — clean coffee that's actually clean", tags: ["mold", "mycotoxin", "clean coffee", "bulletproof", "toxin free"] },
  { title: "Farm Passports", href: "/brewsoul/farms", description: "Origin stories and farm-level transparency", tags: ["farm", "origin", "passport", "ethiopia", "colombia", "kenya", "panama", "coffee"] },
  { title: "Coffee Glossary", href: "/brewsoul/glossary", description: "Coffee terminology encyclopedia — from crema to channeling", tags: ["glossary", "terms", "crema", "extraction", "channeling", "bloom", "coffee"] },
  { title: "Compare Coffees", href: "/brewsoul/compare", description: "Side-by-side coffee comparison tool", tags: ["compare", "versus", "vs", "side by side", "coffee"] },
  // Kristi Klawiter Embezzlement Case Study
  { title: "Convicted Embezzler Kristi Klawiter — $46,795 Stolen", href: "/protecting-your-business", description: "She had two theft convictions. I hired her anyway. She stole $46,795. Court records, FBI report, and the documented case file.", tags: ["kristi klawiter", "klawiter", "kris management", "embezzlement", "embezzle", "fraud", "theft", "steal", "stolen", "con artist", "scam", "scammer", "invoice fraud", "contractor fraud", "unauthorized invoices", "criminal record", "forgery", "monmouth county", "morris county", "new jersey", "asbury", "braintrust", "background check", "protection", "owner protection", "business fraud", "wire fraud", "fbi", "santa monica police", "promissory note", "default", "restitution", "10 red flags", "spot a thief", "con", "grifter", "embezzler", "case study", "protecting your business", "$46795", "46795", "$20000", "upwork", "contractor", "remote contractor", "operations", "kris management llc"] },
  // Psychedelic Readiness Index
  { title: "MAO-B Interaction Matrix", href: "/psychedelic-readiness-index#mao-b", description: "Monoamine oxidase inhibitor interaction guide — selegiline, rasagiline, safinamide wash-out timelines, serotonin syndrome risk, SSRI/SNRI/lithium/tramadol contraindications", tags: ["mao", "maoi", "mao-b", "mao-a", "monoamine oxidase", "monoamine oxidase inhibitor", "selegiline", "rasagiline", "safinamide", "serotonin syndrome", "tyramine", "wash-out", "washout", "drug interaction", "ssri", "snri", "lithium", "tramadol", "parkinsons", "parkinson", "antidepressant", "contraindication", "pharmacology", "enzyme", "serotonin", "dopamine", "norepinephrine", "ayahuasca", "harmine", "harmaline", "dmt", "psychedelic safety"] },
  { title: "Psychedelic Readiness Index", href: "/psychedelic-readiness-index", description: "26-medicine pharmacopoeia and 25-question readiness assessment — find your healing path", tags: ["psychedelic", "readiness", "pri", "psilocybin", "mushrooms", "mdma", "ketamine", "ibogaine", "iboga", "iboga vs ibogaine", "tabernanthe iboga", "ibogaine hcl", "bwiti", "root bark", "flood dose", "ayahuasca", "dmt", "lsd", "mescaline", "peyote", "san pedro", "5-meo-dmt", "bufo", "cannabis", "salvia", "kambo", "rapé", "sananga", "cacao", "kanna", "amanita", "blue lotus", "sassafras", "nitrous oxide", "soma", "healing", "therapy", "psychedelic medicine", "assessment", "harm reduction", "sacred medicine", "plant medicine", "altered state", "consciousness", "microdose", "ceremony"] },
  { title: "PeptideWatch Safety Guide", href: "/peptide-watch", description: "The definitive consumer safety guide — 12 fraud patterns, 18 enforcement actions, 10-question supply chain test, vendor scorecard, role-based checklists for consumers, suppliers, distributors, prescribers, and researchers", tags: ["peptidewatch", "peptide watch", "safety", "guide", "consumer", "fraud", "enforcement", "fda", "doj", "ftc", "itc", "warning letter", "vendor", "scorecard", "checklist", "supply chain", "test", "buyer", "supplier", "distributor", "prescriber", "researcher", "compounder", "compounding", "semaglutide", "tirzepatide", "bpc-157", "peptide sciences", "paradigm peptides", "amino asylum", "empower pharmacy", "finnrick", "coa", "counterfeit", "gray market", "research use only", "safe drugs act", "rfk", "whistleblower", "report", "medwatch", "wall of shame", "three markets", "watchdog"] },
  { title: "Iboga vs Ibogaine Deep Dive", href: "/iboga-ibogaine", description: "The Plant vs The Isolate. Full alkaloid profiles, receptor pharmacology, Bwiti tradition vs clinical protocol, outcomes data, pharma alternatives, supplement stacks", tags: ["iboga", "ibogaine", "ibogaine hcl", "tabernanthe iboga", "bwiti", "noribogaine", "ibogamine", "tabernanthine", "voacangine", "coronaridine", "root bark", "flood dose", "addiction", "opioid", "nmda", "kappa opioid", "sert", "dat", "cardiac", "qt prolongation", "methadone", "suboxone", "buprenorphine", "naltrexone", "gabon", "cameroon", "ceremony", "clinical", "entourage effect", "alkaloid", "deep dive", "psychedelic", "plant medicine", "tbi", "ptsd", "depression", "supplement", "coq10", "magnesium", "integration"] },
  { title: "Mescaline / Peyote Deep Dive", href: "/peyote-mescaline", description: "Full pharmacology, Latuda Mirror, outcomes data (n=452), pharma-to-plant alternatives, supplement stacks, medicine selector", tags: ["mescaline", "peyote", "san pedro", "huachuma", "cactus", "pharmacology", "receptor", "5-ht2a", "serotonin", "latuda", "lurasidone", "antipsychotic", "ssri", "zoloft", "lexapro", "effexor", "wellbutrin", "seroquel", "abilify", "xanax", "lithium", "lamictal", "adderall", "ritalin", "ambien", "gabapentin", "suboxone", "buspar", "hydroxyzine", "trazodone", "supplement", "lions mane", "ashwagandha", "nac", "omega 3", "magnesium", "psychedelic", "plant medicine", "pharma alternative", "deep dive", "outcomes", "depression", "anxiety", "ptsd", "addiction", "integration", "ceremony", "native american church"] },
  /* ── Individual PRI Medicine Deep-Links (?m= ids verified against MEDICINES in lib/content/pri-data.ts) ── */
  { title: "Psilocybin Mushrooms", href: "/psychedelic-readiness-index?m=psilocybin", description: "Classic tryptamine — neuroplasticity, default mode network reset, 6-hour journey", tags: ["psilocybin", "mushrooms", "magic mushrooms", "shrooms", "tryptamine", "neuroplasticity", "depression", "anxiety", "ptsd", "microdose"] },
  { title: "Ayahuasca", href: "/psychedelic-readiness-index?m=ayahuasca", description: "The vine of the soul — DMT + MAO inhibitor, 4-8 hour ceremony, purge and vision", tags: ["ayahuasca", "aya", "dmt", "maoi", "vine", "ceremony", "purge", "amazon", "shipibo", "icaros"] },
  { title: "MDMA Therapy", href: "/psychedelic-readiness-index?m=mdma", description: "FDA Breakthrough Therapy — empathogen for PTSD, trauma processing, couples therapy", tags: ["mdma", "ecstasy", "molly", "empathogen", "ptsd", "maps", "lykos", "trauma", "couples therapy"] },
  { title: "Ketamine", href: "/psychedelic-readiness-index?m=ketamine", description: "NMDA antagonist — rapid antidepressant, dissociative, legal in all 50 states. KAP + IFS therapy. Dr. Beverly Reader.", tags: ["ketamine", "esketamine", "spravato", "nmda", "dissociative", "depression", "suicidal", "infusion", "troches", "kap", "ketamine assisted psychotherapy", "ifs", "internal family systems", "beverly reader", "dr reader", "neuroplasticity", "trauma", "complex ptsd", "integration"] },
  { title: "LSD", href: "/psychedelic-readiness-index?m=lsd", description: "Lysergic acid diethylamide — 8-12 hour serotonergic journey, microdose pioneer", tags: ["lsd", "acid", "lysergic", "hofmann", "serotonin", "microdose", "tab", "blotter"] },
  { title: "DMT / 5-MeO-DMT", href: "/psychedelic-readiness-index?m=dmt", description: "The spirit molecule — 15-minute breakthrough, Bufo alvarius toad medicine", tags: ["dmt", "5-meo-dmt", "bufo", "toad", "spirit molecule", "breakthrough", "nn-dmt", "alvarius"] },
  { title: "Iboga (Whole Plant)", href: "/psychedelic-readiness-index?m=iboga", description: "Tabernanthe iboga root bark — Bwiti sacrament, 12+ alkaloids, 24-48 hour journey", tags: ["iboga", "tabernanthe", "bwiti", "root bark", "gabon", "cameroon", "alkaloid", "noribogaine", "addiction"] },
  { title: "Ibogaine (Isolated Alkaloid)", href: "/psychedelic-readiness-index?m=ibogaine", description: "Ibogaine HCl — clinical isolate, opioid detox, NMDA + kappa opioid, cardiac monitoring required", tags: ["ibogaine", "ibogaine hcl", "opioid", "detox", "addiction", "flood dose", "cardiac", "qt", "clinical"] },
  { title: "Peyote / Mescaline", href: "/psychedelic-readiness-index?m=mescaline", description: "Phenethylamine cactus — 8-12 hours, Native American Church sacrament", tags: ["mescaline", "peyote", "san pedro", "huachuma", "cactus", "phenethylamine", "nac"] },
  { title: "Kambo", href: "/psychedelic-readiness-index?m=kambo", description: "Giant monkey frog peptide — intense purge, immune reset, not a psychedelic", tags: ["kambo", "sapo", "frog", "peptide", "purge", "immune", "phyllomedusa"] },
  { title: "Rapeh (Hape)", href: "/psychedelic-readiness-index?m=rapeh", description: "Sacred tobacco snuff — grounding, clearing, ceremony opener", tags: ["rapeh", "hape", "rapé", "snuff", "tobacco", "mapacho", "grounding"] },
  { title: "Sananga Eye Drops", href: "/psychedelic-readiness-index?m=sananga", description: "Amazonian eye medicine — intense burn, visual clarity, spiritual sight", tags: ["sananga", "eye drops", "tabernaemontana", "vision", "clarity"] },
  { title: "Microdosing Protocol", href: "/psychedelic-readiness-index?m=microdose", description: "Sub-perceptual dosing — Fadiman protocol, Stamets stack, neuroplasticity", tags: ["microdose", "microdosing", "fadiman", "stamets", "stack", "sub-perceptual", "protocol"] },
  { title: "Ceremonial Cannabis", href: "/psychedelic-readiness-index?m=cannabis", description: "Intentional high-dose cannabis — psychedelic threshold, ceremony context", tags: ["cannabis", "marijuana", "thc", "cbd", "ceremonial", "edible", "high dose"] },
  { title: "Ceremonial Cacao", href: "/psychedelic-readiness-index?m=cacao", description: "Heart-opening theobromine — gentle ceremony, emotional processing", tags: ["cacao", "chocolate", "theobromine", "heart", "ceremony", "gentle"] },
  { title: "Amanita muscaria", href: "/psychedelic-readiness-index?m=amanita", description: "Fly agaric mushroom — muscimol, GABA agonist, Siberian shamanic tradition", tags: ["amanita", "muscaria", "fly agaric", "muscimol", "gaba", "ibotenic", "siberian"] },
  { title: "Huachuma (San Pedro)", href: "/psychedelic-readiness-index?m=huachuma", description: "Mescaline cactus — 10-14 hour heart-centered journey, Andean tradition", tags: ["huachuma", "san pedro", "echinopsis", "trichocereus", "mescaline", "andean"] },
  { title: "Salvia divinorum", href: "/psychedelic-readiness-index?m=salvia", description: "Kappa opioid agonist — intense 5-15 minute dissociative, Mazatec tradition", tags: ["salvia", "divinorum", "salvinorin", "kappa", "mazatec", "dissociative"] },
  { title: "Yopo / Vilca", href: "/psychedelic-readiness-index?m=yopo", description: "DMT + 5-MeO-DMT snuff — Amazonian nasal insufflation, intense 30-minute journey", tags: ["yopo", "vilca", "anadenanthera", "bufotenin", "snuff", "amazonian"] },
  { title: "Lion's Mane Stack", href: "/psychedelic-readiness-index?m=lionsmane", description: "Neurotropic mushroom — NGF, BDNF, Stamets stack with psilocybin microdose", tags: ["lions mane", "lion's mane", "hericium", "ngf", "bdnf", "stamets", "neurotropic", "nootropic"] },
  { title: "Iboga Microdose (Root Bark)", href: "/psychedelic-readiness-index?m=ibogamic", description: "Sub-flood whole plant — Bwiti maintenance dose, full alkaloid profile at low dose", tags: ["iboga micro", "iboga microdose", "root bark", "sub-flood", "bwiti", "maintenance"] },
  { title: "Changa (Smokeable Aya)", href: "/psychedelic-readiness-index?m=changa", description: "DMT + MAOI herb blend — 20-45 minute smokeable ayahuasca experience", tags: ["changa", "smokeable", "dmt", "maoi", "julian palmer", "herb blend"] },
  { title: "Caapi Vine Alone", href: "/psychedelic-readiness-index?m=caapi", description: "Banisteriopsis caapi without DMT — gentle MAOI sedation, emotional opening", tags: ["caapi", "banisteriopsis", "vine", "maoi", "harmine", "harmaline", "gentle"] },
  { title: "Vedic / Soma Preparations", href: "/psychedelic-readiness-index?m=soma", description: "Ancient Rigveda sacrament — identity debated, consciousness exploration", tags: ["soma", "vedic", "rigveda", "amanita", "ephedra", "ancient", "sacrament"] },
  { title: "Mapacho (Sacred Tobacco)", href: "/psychedelic-readiness-index?m=mapacho", description: "Nicotiana rustica — 20x nicotine, Amazonian master plant for grounding and protection", tags: ["mapacho", "sacred tobacco", "nicotiana rustica", "grounding", "protection", "amazonian"] },
  // PRI Kava Encyclopedia
  { title: "PRI Kava Encyclopedia", href: "/kava", description: "The definitive kava resource — 10 modules covering origins, science, interactions, assessment, products, and certification", tags: ["kava", "pri kava", "kava encyclopedia", "piper methysticum", "kavalactone", "noble kava", "ceremony", "pacific", "polynesian", "sacred plant", "anxiolytic", "gaba", "threshold", "awa", "yaqona", "sakau"] },
  { title: "Kava Island Origins", href: "/kava/origins", description: "3,000 years of kava culture across the Pacific — Vanuatu, Fiji, Tonga, Samoa, Hawaii, Pohnpei", tags: ["kava origins", "vanuatu", "fiji", "tonga", "samoa", "hawaii", "pohnpei", "yaqona", "awa", "sakau", "noble cultivar", "tudei", "pacific islands", "polynesian", "melanesian", "micronesian", "nakamal", "kava bar"] },
  { title: "Kava Drug Interactions", href: "/kava/interactions", description: "24 substance interactions with kava — CYP450 enzyme inhibition, severity matrix, wash-out timelines", tags: ["kava interaction", "kava drug interaction", "cyp450", "cyp1a2", "cyp2e1", "cyp3a4", "alcohol kava", "benzodiazepine kava", "ssri kava", "opioid kava", "liver", "hepatotoxicity", "contraindication", "medication", "prescription", "wash-out", "severity"] },
  { title: "Kavalactone Science", href: "/kava/science", description: "6 major kavalactones decoded — kavain, dihydrokavain, methysticin, DHM, yangonin, desmethoxyyangonin with chemotype decoder", tags: ["kavalactone", "kavain", "dihydrokavain", "methysticin", "dihydromethysticin", "yangonin", "desmethoxyyangonin", "chemotype", "cultivar", "pharmacology", "gaba", "dopamine", "serotonin", "cox-2", "sodium channel", "calcium channel", "kava science"] },
  { title: "PRI Kava Assessment", href: "/kava/assessment", description: "Five-domain kava readiness scoring — somatic, psychological, relational, cultural, integration — 0 to 100 with ceremony clearance", tags: ["kava assessment", "kava readiness", "pri kava", "somatic readiness", "psychological readiness", "ceremony clearance", "kava score", "kava test", "kava quiz"] },
  { title: "Hawaii ICE Crisis & Awa Recovery", href: "/kava/hawaii", description: "Hawaii's meth crisis meets awa recovery — 410% above national average, pharmacological alignment, cultural argument for kava", tags: ["hawaii", "ice", "meth", "methamphetamine", "awa", "kava hawaii", "harm reduction", "recovery", "crystal meth", "dopamine", "gaba", "native hawaiian", "cultural recovery", "awa ceremony", "big island", "oahu", "maui"] },
  { title: "Kava Myths Debunked", href: "/kava/myths", description: "7 persistent kava myths examined against WHO data, peer-reviewed research, and 3,000 years of traditional use", tags: ["kava myth", "kava liver", "kava hepatotoxicity", "kava addiction", "kava psychedelic", "kava sedative", "kava safety", "kava ban", "europe ban", "who kava", "noble vs tudei", "kava capsule", "kava long term"] },
  { title: "Kava & Caffeine Interactions", href: "/kava/caffeine", description: "Kava inhibits CYP1A2 by 56% — caffeine metabolism, hippie speedball, yerba mate alternative, ceremony cutoff protocol", tags: ["kava caffeine", "cyp1a2", "caffeine metabolism", "hippie speedball", "yerba mate", "coffee kava", "caffeine cutoff", "kava coffee", "stimulant", "energy drink", "matcha kava"] },
  { title: "Kava Product Index", href: "/kava/products", description: "Ceremonial powders, fresh frozen, RTD beverages, supplements, and kava bars — all with PRI ratings and pricing", tags: ["kava product", "buy kava", "kava powder", "kava bar", "kava supplement", "kava capsule", "kava drink", "rtd kava", "fresh frozen kava", "ceremonial kava", "kalm with kava", "bula kava house", "root of happiness", "kavafied", "noble kava", "borongoru", "borogu", "melo melo"] },
  { title: "Kava Facilitator Certification", href: "/kava/certification", description: "12-module, 80-hour certification — Kava Practitioner, Threshold Facilitator, Master Facilitator", tags: ["kava certification", "kava facilitator", "kava practitioner", "threshold facilitator", "master facilitator", "kava training", "kava course", "kava ceremony", "kava preparation", "kava botany", "kava pharmacology", "kava safety", "kava crisis response"] },
  /* ── Attention Theft Manifesto — consolidated single page (Phase 8); the 5
     legacy sub-pages below are repointed to real in-page section anchors,
     not separate routes. ── */
  { title: "Attention Theft Manifesto", href: "/attention-theft", description: "The crusade against spam, cold outreach, and the $997B attention theft economy — economics, weapons, and action", tags: ["attention theft", "manifesto", "spam", "crusade", "email", "cold outreach", "attention economy", "digital pollution", "inbox", "unsolicited", "noise cancel", "communication", "customer service", "trust"] },
  { title: "Attention Economics", href: "/attention-theft#heresy", description: "The $997 billion annual cost of attention theft — 23 minutes per interruption, 65+ hours per person per year", tags: ["attention economics", "spam cost", "productivity loss", "interruption cost", "23 minutes", "attention theft cost", "trillion dollar", "economic theft", "time theft"] },
  { title: "AI Blocker Finder", href: "/attention-theft#blocker-finder", description: "4-question quiz to find your personalized arsenal of AI-powered email defense tools", tags: ["blocker", "ai blocker", "spam filter", "email tools", "sanebox", "superhuman", "clean email", "proton mail", "hey.com", "email defense", "inbox protection"] },
  { title: "Legal Database", href: "/attention-theft#legal", description: "Anti-spam laws worldwide — CAN-SPAM, GDPR, CASL — and the legislation we need next", tags: ["legal", "can-spam", "gdpr", "casl", "anti-spam law", "legislation", "regulation", "ftc", "privacy", "consent", "opt-in", "attention theft law"] },
  { title: "The 10 Weapons", href: "/attention-theft#weapons", description: "Ten actionable weapons to fight attention theft — from zero engagement to the nuclear option", tags: ["weapons", "fight spam", "email defense", "unsubscribe", "block", "report", "email alias", "time block", "public shame", "arsenal"] },
  { title: "Report A Spammer", href: "/attention-theft#report", description: "Public accountability database — name the worst offenders and build the evidence", tags: ["report", "spammer", "accountability", "shame", "forward medical", "cold outreach", "spam report", "complaint", "crusade", "customer service"] },
  { title: "The Facilitator Index — Know Who You Go With", href: "/facilitator-index", description: "Invitation-only, anonymous, philosophy-first instrument for psychedelic practitioners and guides. 108 items across twelve bands. Companion to the Psychedelic Readiness Index.", tags: ["facilitator index", "facilitator", "facilitators", "psychedelic facilitator", "guide", "psychedelic guide", "practitioner", "psychedelic practitioner", "know who you go with", "who you go with", "facilitator assessment", "facilitator instrument", "facilitator vetting", "facilitator philosophy", "facilitator ethics", "facilitator certification", "facilitator map", "facilitator network", "facilitator referral", "facilitator corroboration", "shipibo", "vegetalismo", "santo daime", "uniao do vegetal", "mazatec", "wixarika", "native american church", "bwiti", "ibogaine medical detox", "kambo", "rapeh", "sananga", "amanita", "cacao ceremony", "nakamal", "kava ceremony", "temazcal", "holotropic breathwork", "mdma protocol", "psilocybin trial", "ketamine assisted", "reciprocity gate", "corroboration tokens", "coded identity", "anonymous practitioner", "cedar code", "practitioner map", "five axis map", "closed to me", "preparation arc", "integration arc", "container shape", "screening", "medical clearance", "touch consent", "sliding scale", "referral network", "fireside project", "psychedelic readiness index", "pri", "companion instrument"] },
];
