CREATE TABLE `clock_keeper_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`respondentName` varchar(256),
	`respondentEmail` varchar(320),
	`q1` text,
	`q2` text,
	`q3` text,
	`q4` text,
	`q5` text,
	`q6` text,
	`q7` text,
	`q8` text,
	`q9` text,
	`q10` text,
	`q11` text,
	`q12` text,
	`reframe` text,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `clock_keeper_responses_id` PRIMARY KEY(`id`)
);
