CREATE TABLE `vendor_intake` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplier_id` varchar(36) NOT NULL,
	`stage2_token` varchar(24) NOT NULL,
	`stage` enum('stage1_submitted','stage2_invited','stage2_in_progress','stage2_submitted') NOT NULL DEFAULT 'stage1_submitted',
	`stage2_last_saved_at` timestamp,
	`admin_status` enum('new','reviewing','pursue','pass','approved','rejected') NOT NULL DEFAULT 'new',
	`admin_notes` text,
	`stage1_score` int,
	`total_score` int,
	`score_grade` varchar(2),
	`legal_entity_name` varchar(256) NOT NULL,
	`state_country_of_incorporation` varchar(128) NOT NULL,
	`primary_contact_name` varchar(256) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(64),
	`website` varchar(512),
	`current_peptide_products` text NOT NULL,
	`facility_type` varchar(64) NOT NULL,
	`number_of_employees` varchar(32) NOT NULL,
	`monthly_production_capacity` varchar(256),
	`source_site` varchar(64) NOT NULL DEFAULT 'tonygreenberg',
	`chain_of_custody_capability` varchar(128) NOT NULL,
	`pricing_model` varchar(128) NOT NULL,
	`standard_lead_time` varchar(64) NOT NULL,
	`minimum_order_quantity` varchar(64) NOT NULL,
	`independent_testing_willingness` varchar(128) NOT NULL,
	`facility_classification` varchar(128) NOT NULL,
	`product_labeling_sale_restrictions` varchar(128) NOT NULL,
	`recall_capa_history` varchar(128) NOT NULL,
	`dba_name` varchar(256),
	`year_founded` varchar(8),
	`headquarters_address` text,
	`manufacturing_facility_address` text,
	`contact_title` varchar(256),
	`ownership_principals` text,
	`peptide_synthesis_method` varchar(256),
	`purity_levels_achieved` varchar(256),
	`sterile_fill_capability` varchar(32),
	`cold_chain_storage_capabilities` text,
	`batch_documentation` text,
	`quality_management_system` varchar(128),
	`third_party_testing` varchar(64),
	`testing_lab_name` varchar(256),
	`coa_lot_specific` varchar(32),
	`coa_publicly_viewable` varchar(32),
	`coa_public_link` varchar(512),
	`identity_confirmation_method` varchar(256),
	`testing_protocols` text,
	`stability_testing_program` varchar(64),
	`payment_terms` varchar(256),
	`existing_distribution_channels` text,
	`references` text,
	`pricing_for_top_compounds` text,
	`full_price_list_catalog` text,
	`fda_registration_number` varchar(128),
	`dea_registration` varchar(32),
	`state_licenses` text,
	`buyer_eligibility` text,
	`shipping_jurisdictions` text,
	`last_fda_inspection_date` varchar(32),
	`fda_inspection_outcome` varchar(128),
	`manufacturing_certifications` text,
	`warning_letters_regulatory_disclosure` text,
	`insurance_coverage` text,
	`upload_coa` text,
	`upload_cgmp_cert` text,
	`upload_fda_docs` text,
	`upload_insurance_cert` text,
	`upload_sop` text,
	`upload_additional` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendor_intake_id` PRIMARY KEY(`id`),
	CONSTRAINT `vendor_intake_supplier_id_unique` UNIQUE(`supplier_id`),
	CONSTRAINT `vendor_intake_stage2_token_unique` UNIQUE(`stage2_token`)
);
--> statement-breakpoint
DROP TABLE `vendor_applications`;