CREATE TABLE `article_drafts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`article_slug` varchar(256) NOT NULL,
	`original_title` varchar(512) NOT NULL,
	`v2_content` text,
	`central_idea` text,
	`soul_sentence` text,
	`scorecard` text,
	`improvements` text,
	`change_log` text,
	`new_prose_table` text,
	`title_options` text,
	`subtitle_options` text,
	`pull_quotes` text,
	`social_excerpts` text,
	`illustration_idea` text,
	`journey_stage` varchar(64),
	`stage_justification` text,
	`journey_line` text,
	`divergence_notes` text,
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`completed_workstreams` varchar(128) NOT NULL DEFAULT '',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	`published_at` timestamp,
	`created_by` int,
	CONSTRAINT `article_drafts_id` PRIMARY KEY(`id`)
);
