/**
 * IBOGA COMPASS — Facility Database
 * Real iboga/ibogaine treatment centers with dimension scores (0-10).
 * Scores are based on publicly available information, published reviews,
 * and the Compass v2 scoring methodology.
 *
 * Each facility is scored across the 10 dimensions:
 * 1. Medical Safety
 * 2. Clinical Track Record
 * 3. Bwiti Authenticity
 * 4. Integration Depth
 * 5. Specialty Fit (varies by user answers)
 * 6. Facility Quality
 * 7. Cost-to-Value
 * 8. Nagoya Reciprocity
 * 9. Access & Intake
 * 10. Reputation
 */

export interface Facility {
  id: string;
  name: string;
  shortName: string;
  location: string;
  country: string;
  region: "mexico" | "costa-rica" | "portugal" | "spain" | "gabon" | "usa" | "bahamas" | "malta";
  website: string;
  priceRange: string;
  priceMin: number; // USD
  priceMax: number; // USD
  durationDays: [number, number]; // min, max
  approach: "medical" | "hybrid" | "ceremonial" | "bwiti";
  specialties: string[];
  languages: string[];
  familyProgram: boolean;
  veganFriendly: boolean;
  veteranFocus: boolean;
  /** Dimension scores 1-10 */
  medicalSafety: number;
  clinicalTrackRecord: number;
  bwitiAuthenticity: number;
  integrationDepth: number;
  specialtyFit: number; // base score, adjusted by user answers
  facilityQuality: number;
  costToValue: number;
  nagoyaReciprocity: number;
  accessIntake: number;
  reputation: number;
  /** Brief description for results */
  tagline: string;
  highlights: string[];
}

export const FACILITIES: Facility[] = [
  {
    id: "ambio",
    name: "Ambio Life Sciences",
    shortName: "Ambio",
    location: "Tijuana, Mexico & Malta",
    country: "Mexico",
    region: "mexico",
    website: "https://ambio.life",
    priceRange: "$7,500 – $15,000",
    priceMin: 7500,
    priceMax: 15000,
    durationDays: [7, 14],
    approach: "medical",
    specialties: ["opioids", "polydrug", "benzos", "meth", "alcohol", "process-addiction"],
    languages: ["English", "Spanish"],
    familyProgram: true,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 9,
    clinicalTrackRecord: 9,
    bwitiAuthenticity: 2,
    integrationDepth: 8,
    specialtyFit: 8,
    facilityQuality: 8,
    costToValue: 7,
    nagoyaReciprocity: 3,
    accessIntake: 8,
    reputation: 9,
    tagline: "The global leader in integrative ibogaine treatment — broad addiction expertise with hospital-grade safety.",
    highlights: [
      "12+ years operating, thousands of treatments",
      "Full cardiac monitoring with on-site MD",
      "Benzo and polydrug taper specialization",
      "Dual locations: Mexico (Tijuana) and Malta (Europe)",
    ],
  },
  {
    id: "tmw",
    name: "The Mission Within",
    shortName: "TMW",
    location: "San Diego area, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://missionwithin.org",
    priceRange: "$0 – $5,000 (veteran-subsidized)",
    priceMin: 0,
    priceMax: 5000,
    durationDays: [4, 7],
    approach: "medical",
    specialties: ["ptsd", "tbi", "veteran-trauma", "military"],
    languages: ["English"],
    familyProgram: true,
    veganFriendly: false,
    veteranFocus: true,
    medicalSafety: 9,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 1,
    integrationDepth: 9,
    specialtyFit: 7,
    facilityQuality: 7,
    costToValue: 10,
    nagoyaReciprocity: 2,
    accessIntake: 7,
    reputation: 9,
    tagline: "A future free from veteran suicide — clinical psychedelic program for military veterans and first responders.",
    highlights: [
      "1,200+ veterans treated",
      "6-week program: online therapy + 4-day medicine retreat",
      "Subsidized or free for qualifying veterans",
      "Stanford-studied ibogaine for TBI outcomes",
    ],
  },
  {
    id: "beond",
    name: "Beond Ibogaine",
    shortName: "Beond",
    location: "Cancún, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://beondibogaine.com",
    priceRange: "$12,000 – $25,000",
    priceMin: 12000,
    priceMax: 25000,
    durationDays: [7, 10],
    approach: "medical",
    specialties: ["opioids", "alcohol", "trauma", "depression", "process-addiction"],
    languages: ["English", "Spanish"],
    familyProgram: true,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 10,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 1,
    integrationDepth: 8,
    specialtyFit: 8,
    facilityQuality: 10,
    costToValue: 5,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 9,
    tagline: "World's leading medically licensed ibogaine clinic — hospital-grade care in luxury Cancún setting.",
    highlights: [
      "Full medical license with hospital affiliation",
      "Luxury beachfront accommodations",
      "Comprehensive cardiac monitoring suite",
      "Process addiction and trauma specialization",
    ],
  },
  {
    id: "clear-sky",
    name: "Clear Sky Recovery",
    shortName: "Clear Sky",
    location: "Cancún, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://clearskyrecovery.com",
    priceRange: "$5,500 – $8,000",
    priceMin: 5500,
    priceMax: 8000,
    durationDays: [5, 7],
    approach: "medical",
    specialties: ["opioids", "alcohol", "cocaine", "polydrug"],
    languages: ["English", "Spanish"],
    familyProgram: true,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 9,
    clinicalTrackRecord: 9,
    bwitiAuthenticity: 1,
    integrationDepth: 6,
    specialtyFit: 7,
    facilityQuality: 8,
    costToValue: 8,
    nagoyaReciprocity: 2,
    accessIntake: 9,
    reputation: 8,
    tagline: "17 years of medically supervised ibogaine detox — one of the longest-running clinics in Mexico.",
    highlights: [
      "17+ years operating under Dr. Alberto Sola",
      "Oceanfront luxury setting in Cancún",
      "Rapid intake process",
      "Strong opioid and polydrug detox track record",
    ],
  },
  {
    id: "dardashti",
    name: "Ibogaine by David Dardashti",
    shortName: "Dardashti",
    location: "Rosarito, Mexico (near San Diego)",
    country: "Mexico",
    region: "mexico",
    website: "https://ibogaineclinic.com",
    priceRange: "$6,000 – $12,000",
    priceMin: 6000,
    priceMax: 12000,
    durationDays: [5, 10],
    approach: "medical",
    specialties: ["opioids", "opioid-replacement", "cocaine", "meth", "prescription-stimulants", "long-term-addiction"],
    languages: ["English", "Spanish", "Hebrew"],
    familyProgram: true,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 9,
    clinicalTrackRecord: 10,
    bwitiAuthenticity: 1,
    integrationDepth: 7,
    specialtyFit: 9,
    facilityQuality: 7,
    costToValue: 7,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 9,
    tagline: "Pioneer ibogaine protocol developer — 20+ years treating severe opioid and stimulant addiction.",
    highlights: [
      "20+ years of ibogaine research and treatment",
      "Proprietary protocol for opioid replacement taper",
      "Suboxone/methadone specialization",
      "Close to US border for easy access",
    ],
  },
  {
    id: "tabula-rasa",
    name: "Tabula Rasa Retreat",
    shortName: "Tabula Rasa",
    location: "Alentejo, Portugal",
    country: "Portugal",
    region: "portugal",
    website: "https://www.tabularasaretreat.com",
    priceRange: "€5,500 – €7,500 ($6,000 – $8,200)",
    priceMin: 6000,
    priceMax: 8200,
    durationDays: [7, 14],
    approach: "hybrid",
    specialties: ["alcohol", "gambling", "benzos", "process-addiction", "cocaine"],
    languages: ["English", "Portuguese", "French"],
    familyProgram: false,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 4,
    integrationDepth: 8,
    specialtyFit: 8,
    facilityQuality: 8,
    costToValue: 8,
    nagoyaReciprocity: 4,
    accessIntake: 7,
    reputation: 8,
    tagline: "Portugal's leading ibogaine retreat — explicit gambling and alcohol programs with European medical standards.",
    highlights: [
      "Explicit gambling addiction program",
      "European medical oversight",
      "Rural Portuguese setting for deep healing",
      "Strong integration and aftercare network",
    ],
  },
  {
    id: "experience-ibogaine",
    name: "Experience Ibogaine",
    shortName: "Experience Ibogaine",
    location: "Tijuana, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://www.experienceibogaine.com",
    priceRange: "$5,000 – $12,000",
    priceMin: 5000,
    priceMax: 12000,
    durationDays: [7, 16],
    approach: "medical",
    specialties: ["cocaine", "meth", "polydrug", "opioids"],
    languages: ["English", "Spanish"],
    familyProgram: false,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 1,
    integrationDepth: 7,
    specialtyFit: 9,
    facilityQuality: 7,
    costToValue: 7,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 8,
    tagline: "Specialized 16-day polydrug program — cocaine and methamphetamine addiction expertise.",
    highlights: [
      "16-day extended program for polydrug users",
      "Cocaine and meth specialization",
      "Medical team with ibogaine-specific training",
      "Close to US border",
    ],
  },
  {
    id: "iboga-wellness",
    name: "Iboga Wellness Center",
    shortName: "Iboga Wellness",
    location: "Costa Rica",
    country: "Costa Rica",
    region: "costa-rica",
    website: "https://ibogawellness.com",
    priceRange: "$4,500 – $8,000",
    priceMin: 4500,
    priceMax: 8000,
    durationDays: [7, 8],
    approach: "ceremonial",
    specialties: ["spiritual", "cannabis", "depression", "life-reset"],
    languages: ["English"],
    familyProgram: false,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 6,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 8,
    integrationDepth: 7,
    specialtyFit: 7,
    facilityQuality: 7,
    costToValue: 7,
    nagoyaReciprocity: 7,
    accessIntake: 7,
    reputation: 8,
    tagline: "The oldest iboga retreat center in the West — traditional Bwiti ceremonies in Costa Rica since 2009.",
    highlights: [
      "Oldest Western iboga center (since 2009)",
      "Two traditional Bwiti ceremonies per retreat",
      "Levi Barker — trained in Gabon",
      "Spiritual and life-reset focus",
    ],
  },
  {
    id: "bwiti-house",
    name: "Bwiti House — Moughenda's Village",
    shortName: "Bwiti House",
    location: "Gabon, Africa",
    country: "Gabon",
    region: "gabon",
    website: "https://www.bwitihouse.com",
    priceRange: "$5,000 – $8,000",
    priceMin: 5000,
    priceMax: 8000,
    durationDays: [14, 14],
    approach: "bwiti",
    specialties: ["spiritual", "bwiti-initiation", "soul-work", "identity-reset"],
    languages: ["French", "Fang", "English (limited)"],
    familyProgram: false,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 4,
    clinicalTrackRecord: 7,
    bwitiAuthenticity: 10,
    integrationDepth: 8,
    specialtyFit: 6,
    facilityQuality: 4,
    costToValue: 7,
    nagoyaReciprocity: 10,
    accessIntake: 5,
    reputation: 9,
    tagline: "The source — 10th-generation Bwiti shaman Moughenda Mikala's village in Gabon since 1990.",
    highlights: [
      "10th-generation Missoko Bwiti lineage",
      "14-day full initiation program",
      "Direct reciprocity to Gabonese stewards",
      "The gold standard for Bwiti authenticity",
    ],
  },
  {
    id: "root-healing",
    name: "Root Healing",
    shortName: "Root Healing",
    location: "Sintra, Portugal",
    country: "Portugal",
    region: "portugal",
    website: "https://www.roothealing.com",
    priceRange: "$6,000 – $10,000",
    priceMin: 6000,
    priceMax: 10000,
    durationDays: [7, 10],
    approach: "hybrid",
    specialties: ["spiritual", "cannabis", "nicotine", "depression", "life-reset"],
    languages: ["English", "Portuguese", "French"],
    familyProgram: false,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 7,
    bwitiAuthenticity: 8,
    integrationDepth: 8,
    specialtyFit: 7,
    facilityQuality: 8,
    costToValue: 7,
    nagoyaReciprocity: 8,
    accessIntake: 7,
    reputation: 7,
    tagline: "Ibogaine-grade safety meets lineage-led care — where ancient Bwiti tradition meets modern healing in Portugal.",
    highlights: [
      "Bwiti-trained facilitators with medical oversight",
      "Beautiful Sintra, Portugal setting",
      "Strong Nagoya reciprocity commitment",
      "Hybrid approach: ceremony + medical safety",
    ],
  },
  {
    id: "new-roots",
    name: "New Roots Ibogaine",
    shortName: "New Roots",
    location: "Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://newrootsibogaine.com",
    priceRange: "$4,500 – $7,000",
    priceMin: 4500,
    priceMax: 7000,
    durationDays: [5, 7],
    approach: "medical",
    specialties: ["opioids", "opioid-replacement", "depression"],
    languages: ["English", "Spanish"],
    familyProgram: false,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 7,
    clinicalTrackRecord: 7,
    bwitiAuthenticity: 1,
    integrationDepth: 6,
    specialtyFit: 7,
    facilityQuality: 7,
    costToValue: 8,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 7,
    tagline: "Personalized holistic ibogaine treatment in Mexico — strong medical screening and opioid replacement expertise.",
    highlights: [
      "Comprehensive pre-treatment medical testing",
      "Opioid replacement (Suboxone) specialization",
      "Holistic aftercare approach",
      "Affordable pricing with strong value",
    ],
  },
  {
    id: "transcend",
    name: "Transcend Ibogaine",
    shortName: "Transcend",
    location: "Cancún, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://transcendibogaine.com",
    priceRange: "$6,000 – $10,000",
    priceMin: 6000,
    priceMax: 10000,
    durationDays: [5, 7],
    approach: "medical",
    specialties: ["opioids", "alcohol", "depression", "anxiety"],
    languages: ["English", "Spanish"],
    familyProgram: true,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 7,
    bwitiAuthenticity: 1,
    integrationDepth: 7,
    specialtyFit: 7,
    facilityQuality: 8,
    costToValue: 7,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 7,
    tagline: "Safe and effective ibogaine therapy in Cancún — serving US clients with comprehensive medical oversight.",
    highlights: [
      "Full medical team with cardiac monitoring",
      "Cancún location with modern facilities",
      "Family program available",
      "Strong aftercare coordination",
    ],
  },
  {
    id: "avante",
    name: "Avante Ibogaine Institute",
    shortName: "Avante",
    location: "Nassau, Bahamas",
    country: "Bahamas",
    region: "bahamas",
    website: "https://avanteibogaine.com",
    priceRange: "$8,000 – $15,000",
    priceMin: 8000,
    priceMax: 15000,
    durationDays: [7, 14],
    approach: "medical",
    specialties: ["opioids", "alcohol", "depression", "ptsd"],
    languages: ["English"],
    familyProgram: true,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 1,
    integrationDepth: 7,
    specialtyFit: 7,
    facilityQuality: 9,
    costToValue: 6,
    nagoyaReciprocity: 2,
    accessIntake: 7,
    reputation: 8,
    tagline: "13+ years of clinical ibogaine treatment on the beach in Nassau — luxury setting with medical rigor.",
    highlights: [
      "13+ years operating",
      "Beachfront luxury in the Bahamas",
      "Full cardiac monitoring",
      "Gourmet dining and private rooms",
    ],
  },
  {
    id: "crossroads",
    name: "Crossroads Treatment Center",
    shortName: "Crossroads",
    location: "Tijuana, Mexico",
    country: "Mexico",
    region: "mexico",
    website: "https://crossroadstreatmentcenter.com",
    priceRange: "$5,000 – $9,000",
    priceMin: 5000,
    priceMax: 9000,
    durationDays: [5, 7],
    approach: "medical",
    specialties: ["opioids", "alcohol", "cocaine"],
    languages: ["English", "Spanish"],
    familyProgram: false,
    veganFriendly: false,
    veteranFocus: false,
    medicalSafety: 8,
    clinicalTrackRecord: 8,
    bwitiAuthenticity: 1,
    integrationDepth: 6,
    specialtyFit: 7,
    facilityQuality: 7,
    costToValue: 7,
    nagoyaReciprocity: 2,
    accessIntake: 8,
    reputation: 7,
    tagline: "Dr. Martin Polanco's 15+ year ibogaine practice — strong medical foundation for substance detox.",
    highlights: [
      "Dr. Martin Polanco — 15+ years experience",
      "Medical team with ibogaine expertise",
      "Close to US border",
      "Alcohol and opioid specialization",
    ],
  },
  {
    id: "awakening-soul",
    name: "Awakening Soul",
    shortName: "Awakening Soul",
    location: "Costa Rica",
    country: "Costa Rica",
    region: "costa-rica",
    website: "https://awakeningsoul.com",
    priceRange: "$4,000 – $7,000",
    priceMin: 4000,
    priceMax: 7000,
    durationDays: [7, 10],
    approach: "ceremonial",
    specialties: ["spiritual", "cannabis", "depression", "life-reset"],
    languages: ["English"],
    familyProgram: false,
    veganFriendly: true,
    veteranFocus: false,
    medicalSafety: 5,
    clinicalTrackRecord: 6,
    bwitiAuthenticity: 7,
    integrationDepth: 7,
    specialtyFit: 6,
    facilityQuality: 7,
    costToValue: 7,
    nagoyaReciprocity: 6,
    accessIntake: 7,
    reputation: 6,
    tagline: "Ceremonial iboga retreat in Costa Rica — spiritual healing and life reset in a natural setting.",
    highlights: [
      "Ceremonial approach with Bwiti influence",
      "Costa Rica natural setting",
      "Spiritual and life-reset focus",
      "Plant-based cuisine available",
    ],
  },
];

/**
 * Substance-to-facility bonus mapping
 * Maps substance selections to facility bonus points
 */
export interface SubstanceBonus {
  substanceKey: string;
  facilityBonuses: { facilityId: string; bonus: number }[];
}

export const SUBSTANCE_BONUSES: SubstanceBonus[] = [
  {
    substanceKey: "opioids",
    facilityBonuses: [
      { facilityId: "ambio", bonus: 5 },
      { facilityId: "dardashti", bonus: 5 },
      { facilityId: "tmw", bonus: 4 },
      { facilityId: "tabula-rasa", bonus: 4 },
      { facilityId: "clear-sky", bonus: 4 },
    ],
  },
  {
    substanceKey: "opioid-replacement",
    facilityBonuses: [
      { facilityId: "dardashti", bonus: 10 },
      { facilityId: "ambio", bonus: 5 },
      { facilityId: "new-roots", bonus: 4 },
    ],
  },
  {
    substanceKey: "alcohol",
    facilityBonuses: [
      { facilityId: "tabula-rasa", bonus: 5 },
      { facilityId: "clear-sky", bonus: 4 },
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "beond", bonus: 3 },
      { facilityId: "crossroads", bonus: 3 },
    ],
  },
  {
    substanceKey: "cocaine",
    facilityBonuses: [
      { facilityId: "experience-ibogaine", bonus: 8 },
      { facilityId: "dardashti", bonus: 5 },
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "beond", bonus: 3 },
      { facilityId: "clear-sky", bonus: 3 },
    ],
  },
  {
    substanceKey: "meth",
    facilityBonuses: [
      { facilityId: "experience-ibogaine", bonus: 6 },
      { facilityId: "ambio", bonus: 5 },
      { facilityId: "clear-sky", bonus: 4 },
      { facilityId: "dardashti", bonus: 4 },
    ],
  },
  {
    substanceKey: "cannabis",
    facilityBonuses: [
      { facilityId: "iboga-wellness", bonus: 4 },
      { facilityId: "root-healing", bonus: 3 },
      { facilityId: "awakening-soul", bonus: 3 },
    ],
  },
  {
    substanceKey: "nicotine",
    facilityBonuses: [
      { facilityId: "ambio", bonus: 3 },
      { facilityId: "iboga-wellness", bonus: 2 },
      { facilityId: "root-healing", bonus: 2 },
    ],
  },
  {
    substanceKey: "prescription-stimulants",
    facilityBonuses: [
      { facilityId: "dardashti", bonus: 5 },
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "beond", bonus: 3 },
    ],
  },
  {
    substanceKey: "benzos",
    facilityBonuses: [
      { facilityId: "ambio", bonus: 5 },
      { facilityId: "tabula-rasa", bonus: 4 },
      { facilityId: "dardashti", bonus: 4 },
    ],
  },
  {
    substanceKey: "ketamine",
    facilityBonuses: [
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "beond", bonus: 3 },
    ],
  },
  {
    substanceKey: "mdma",
    facilityBonuses: [
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "beond", bonus: 3 },
    ],
  },
  {
    substanceKey: "polydrug",
    facilityBonuses: [
      { facilityId: "experience-ibogaine", bonus: 8 },
      { facilityId: "ambio", bonus: 5 },
      { facilityId: "clear-sky", bonus: 4 },
      { facilityId: "dardashti", bonus: 4 },
    ],
  },
  {
    substanceKey: "process-addiction",
    facilityBonuses: [
      { facilityId: "tabula-rasa", bonus: 6 },
      { facilityId: "ambio", bonus: 4 },
      { facilityId: "iboga-wellness", bonus: 3 },
      { facilityId: "root-healing", bonus: 3 },
    ],
  },
  {
    substanceKey: "none",
    facilityBonuses: [
      { facilityId: "iboga-wellness", bonus: 4 },
      { facilityId: "bwiti-house", bonus: 3 },
      { facilityId: "root-healing", bonus: 3 },
    ],
  },
];
