import Link from "next/link";
import { FEATURED_THEMES, THEME_MAP } from "@/lib/content/theme-map";

// Precomposed literal classes, one per theme — see CONTRIBUTING.md's rule on
// dynamic Tailwind classes. A fragment-assembled `text-[${hex}]` never gets
// scanned/generated by Tailwind.
const THEME_TEXT_CLASSES: Record<string, string> = {
  "Systems & Innovation": "text-[#4682B4]",
  "Business & Capital": "text-[#8B6914]",
  "Culture & Communication": "text-[#9B2335]",
  "The Crusades": "text-[#B22222]",
};

// Ported from legacy client/src/pages/Blog.tsx's "Core Themes". Legacy set
// filter state via onClick + scrolled to the archive; here each card is a
// plain link to "/?theme=<key>#essays-archive" and HomeArchive (a Client
// Component) reads the `theme` search param to preset its filter — no
// cross-component client state needed for what's fundamentally a navigation.
export function CoreThemes() {
  return (
    <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="mb-5">
        <h2 className="font-heading text-3xl font-bold text-foreground">Core Themes</h2>
        <p className="text-muted-foreground">
          Six lenses on a life spent building bridges between what is and what could be
        </p>
        <div className="mt-2 h-0.75 w-10 bg-brand-gold" />
      </div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {FEATURED_THEMES.map((theme) => {
          const count = (THEME_MAP[theme.key] || []).length;
          return (
            <Link
              key={theme.key}
              href={`/?theme=${encodeURIComponent(theme.key)}#essays-archive`}
              className="rounded-md border border-border bg-card p-4 transition-shadow hover:shadow-md"
            >
              <theme.icon
                className={`mb-1.5 size-6 ${THEME_TEXT_CLASSES[theme.key] ?? "text-brand-gold"}`}
                strokeWidth={1.75}
              />
              <h3 className="mb-1 font-heading text-lg font-bold text-foreground">{theme.key}</h3>
              <p className="mb-1.5 text-sm text-muted-foreground">{theme.description}</p>
              <span
                className={`font-mono text-xs tracking-wide uppercase ${THEME_TEXT_CLASSES[theme.key] ?? "text-brand-gold"}`}
              >
                {count} ESSAYS →
              </span>
            </Link>
          );
        })}
      </div>
    </section>
  );
}
