import Link from "next/link";
import { FEATURED_THEMES } from "@/lib/content/theme-map";
import { ArrowRight } from "lucide-react";

// Precomposed literal classes, one per theme — see CONTRIBUTING.md's rule on
// dynamic Tailwind classes. A fragment-assembled `text-[${hex}]` never gets
// scanned/generated by Tailwind.
const THEME_TEXT_CLASSES: Record<string, string> = {
  "Systems & Innovation": "text-[#427AA9]",
  "Business & Capital": "text-[#836311]",
  "Culture & Communication": "text-[#9B2335]",
  "The Crusades": "text-[#B22222]",
};

// The intro's count follows the cards actually shown (legacy said "Six" over
// four cards).
const LENS_WORDS: Record<number, string> = { 2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six", 7: "Seven", 8: "Eight" };

// Ported from legacy client/src/pages/Blog.tsx's "Core Themes". Legacy set a
// filter on the archive below; here each card links to the theme's real
// category page (crawlable, and the count is that category's actual post
// count, so it matches the archive's category pills). `categoryCounts` is
// keyed by category slug, computed in app/page.tsx from the posts it fetches.
export function CoreThemes({ categoryCounts }: { categoryCounts: Record<string, number> }) {
  return (
    <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="mb-5">
        <h2 className="font-heading text-3xl font-bold text-foreground">Core Themes</h2>
        <p className="text-muted-foreground">
          {LENS_WORDS[FEATURED_THEMES.length] ?? FEATURED_THEMES.length} lenses on a life spent building bridges between what is and what could be
        </p>
        <div className="mt-2 h-0.75 w-10 bg-brand-gold" />
      </div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {FEATURED_THEMES.map((theme) => {
          const count = categoryCounts[theme.categorySlug] ?? 0;
          return (
            <Link
              key={theme.key}
              href={`/blog/category/${theme.categorySlug}`}
              className="rounded-md border border-border bg-card p-4 transition-shadow hover:shadow-md"
            >
              <theme.icon
                aria-hidden="true"
                className={`mb-1.5 size-6 ${THEME_TEXT_CLASSES[theme.key] ?? "text-brand-gold"}`}
                strokeWidth={1.75}
              />
              <h3 className="mb-1 font-heading text-lg font-bold text-foreground">{theme.key}</h3>
              <p className="mb-1.5 text-sm text-muted-foreground">{theme.description}</p>
              <span
                className={`inline-flex items-center gap-1 font-mono text-xs tracking-wide uppercase ${THEME_TEXT_CLASSES[theme.key] ?? "text-brand-gold"}`}
              >
                {count} ESSAYS
                <ArrowRight aria-hidden="true" className="size-3.5" />
              </span>
            </Link>
          );
        })}
      </div>
    </section>
  );
}
