// One-off (2026-10-07): the images in legacy BlogPost.tsx's "Elixir of Life
// Collection" block on `elixir-of-life-device-and-journey`: the two product
// photos (off the legacy image proxy) and the two "scan to order" QR codes
// (generated by api.qrserver.com on live; saved once here so the page
// doesn't call an outside service). Uploads to Sanity only; prints the URLs
// wired into src/components/blog/elixir-collection.tsx.
//
// Usage: pnpm tsx scripts/rescue-2026-10-07-elixir-images.ts
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "next-sanity";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
process.loadEnvFile(path.join(__dirname, "../.env.local"));

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
});

const qr = (url: string) =>
  `https://api.qrserver.com/v1/create-qr-code/?size=360x360&data=${encodeURIComponent(url)}&color=8B6914&bgcolor=FAFAF7`;
const SOURCES: [string, string][] = [
  ["elixir-golden-rudraksha.webp", "https://tonygreenberg.com/api/img/site-006-elixir-golden-rudraksha_f3662a8d_bde0c6be27_c3c3ef02.webp"],
  ["elixir-meditation-set.webp", "https://tonygreenberg.com/api/img/site-007-elixir-meditation-hat_74c24d62_c5f89f9917_38403db2.webp"],
  ["elixir-qr-golden-rudraksha.png", qr("https://www.elixiroflife.fr/en/product-page/golden-rudraksha")],
  ["elixir-qr-meditation-set.png", qr("https://www.elixiroflife.fr/en/product-page/elixir-of-life-alchemy-meditation-therapy")],
];

async function main() {
  for (const [filename, url] of SOURCES) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
    const asset = await client.assets.upload("image", Buffer.from(await res.arrayBuffer()), { filename });
    console.log(`${filename}: ${asset.url} (${asset.metadata?.dimensions?.width}x${asset.metadata?.dimensions?.height}, ${asset.size} bytes)`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
