// One-off (2026-09-29): rescues every Manus-hosted image/video the legacy app
// referenced (`/api/img/*`, `/manus-storage/*` on tonygreenberg.com) into
// Sanity before Manus is decommissioned. Each file is uploaded as a plain
// Sanity asset — Sanity dedupes by SHA-1, so re-running is safe and assets
// already rescued by earlier scripts are returned, not duplicated.
//
// It doesn't wire anything into pages. It writes a manifest
// (docs/ai/manus-media-rescue.md) mapping each legacy filename → the legacy
// source files that used it → its new Sanity URL, so each page can be
// switched over deliberately (Phase 13), with real alt text.
// Usage: pnpm tsx scripts/rescue-manus-media.ts [--dry-run]
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "next-sanity";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
process.loadEnvFile(path.join(ROOT, ".env.local"));
const DRY_RUN = process.argv.includes("--dry-run");

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
});

const LEGACY = path.join(ROOT, "_legacy-manus-app/client");
const refs = execSync(
  `grep -rhoE "/api/img/[A-Za-z0-9._-]+|/manus-storage/[A-Za-z0-9._-]+" "${LEGACY}/src" "${LEGACY}/public" || true`,
  { encoding: "utf8" },
)
  .split("\n")
  .filter(Boolean);
const unique = [...new Set(refs)].sort();

function usedIn(ref: string): string[] {
  const out = execSync(`grep -rlF "${ref}" "${LEGACY}/src" "${LEGACY}/public" || true`, { encoding: "utf8" });
  return out
    .split("\n")
    .filter(Boolean)
    .map((f) => path.relative(ROOT, f));
}

// Sniff the real format — the proxy often serves WebP bytes under a .jpg name.
function sniff(buf: Buffer): { kind: "image" | "file"; ext: string } {
  if (buf.subarray(0, 4).toString() === "RIFF" && buf.subarray(8, 12).toString() === "WEBP") return { kind: "image", ext: "webp" };
  if (buf[0] === 0xff && buf[1] === 0xd8) return { kind: "image", ext: "jpg" };
  if (buf.subarray(1, 4).toString() === "PNG") return { kind: "image", ext: "png" };
  if (buf.subarray(0, 4).toString() === "GIF8") return { kind: "image", ext: "gif" };
  if (buf.subarray(4, 8).toString() === "ftyp") {
    const brand = buf.subarray(8, 12).toString();
    return brand.startsWith("avi") ? { kind: "image", ext: "avif" } : { kind: "file", ext: "mov" };
  }
  return { kind: "file", ext: "bin" };
}

type Row = { ref: string; status: string; sanityUrl: string | null; usedIn: string[] };

async function run() {
  const rows: Row[] = [];
  for (const ref of unique) {
    const row: Row = { ref, status: "", sanityUrl: null, usedIn: usedIn(ref) };
    try {
      const res = await fetch(`https://tonygreenberg.com${ref}`);
      if (!res.ok) {
        row.status = `gone (HTTP ${res.status})`;
      } else {
        const buf = Buffer.from(await res.arrayBuffer());
        const { kind, ext } = sniff(buf);
        const filename = path.basename(ref).replace(/\.[a-z0-9]+$/i, "") + "." + ext;
        if (DRY_RUN) {
          row.status = `would upload (${kind}, ${ext}, ${buf.length} bytes)`;
        } else {
          const asset = await client.assets.upload(kind, buf, { filename });
          row.sanityUrl = asset.url;
          row.status = "in Sanity";
        }
      }
    } catch (err) {
      row.status = `error: ${err instanceof Error ? err.message : String(err)}`;
    }
    console.log(`${row.status.padEnd(14)} ${ref}`);
    rows.push(row);
  }

  if (DRY_RUN) return;
  const lines = [
    "# Manus media rescue manifest",
    "",
    "> Generated by `scripts/rescue-manus-media.ts` on " + new Date().toISOString().slice(0, 10) + ". Every Manus-hosted image/video the legacy app referenced, rescued into Sanity before Manus is decommissioned. **Not wired into pages yet** unless the page already used the same Sanity asset. To use one: copy its Sanity URL into the ported page (via `next/image`), with real alt text, and tick it off in `NEXTJS-MIGRATION-TODO.md` Phase 13.",
    "",
    `Total: ${rows.length} · in Sanity: ${rows.filter((r) => r.sanityUrl).length} · gone: ${rows.filter((r) => r.status.startsWith("gone")).length}`,
    "",
    "| Legacy path | Used in (legacy source) | Sanity URL | Status |",
    "| --- | --- | --- | --- |",
    ...rows.map(
      (r) =>
        `| \`${r.ref}\` | ${r.usedIn.map((u) => `\`${u.replace("_legacy-manus-app/client/", "")}\``).join("<br>") || "—"} | ${r.sanityUrl ?? "—"} | ${r.status} |`,
    ),
    "",
  ];
  fs.writeFileSync(path.join(ROOT, "docs/ai/manus-media-rescue.md"), lines.join("\n"));
  console.log("\nWrote docs/ai/manus-media-rescue.md");
}

run();
