/**
 * PRI Safety Data — Contraindications, Side Effects, Drug Interactions, Legal Status
 * This is NOT medical advice. Community-aggregated information for harm reduction only.
 */

export interface MedicineSafety {
  contraindications: string[];
  sideEffects: string[];
  drugInteractions: string[];
  safetyWarning: string;
  legalStatus: string;
}

export const SAFETY_DATA: Record<string, MedicineSafety> = {
  psilocybin: {
    contraindications: [
      "Personal or family history of psychosis, schizophrenia, or bipolar I disorder",
      "Active suicidal ideation without professional supervision",
      "Severe cardiovascular conditions (rare but caution warranted)",
      "Pregnancy or breastfeeding",
      "Under 18 years of age",
    ],
    sideEffects: [
      "Nausea and gastrointestinal discomfort (onset phase)",
      "Anxiety or panic during peak (manageable with proper set/setting)",
      "Temporary perceptual disturbances (visual trails, synesthesia)",
      "Emotional flooding — intense grief, fear, or euphoria",
      "Headache (typically mild, post-experience)",
      "Fatigue for 24–48 hours after",
      "Rare: HPPD (Hallucinogen Persisting Perception Disorder)",
    ],
    drugInteractions: [
      "SSRIs (fluoxetine, sertraline, etc.) — significantly reduce effects; serotonin syndrome risk low but documented",
      "MAOIs — dangerous potentiation; do NOT combine",
      "Lithium — seizure risk; ABSOLUTE contraindication",
      "Tramadol — seizure risk; do NOT combine",
      "Cannabis — unpredictable potentiation of anxiety",
    ],
    safetyWarning: "Psilocybin is generally considered one of the safest psychedelics physiologically. The primary risks are psychological. A trusted guide, proper screening, and integration support dramatically reduce adverse outcomes. Never use alone for the first time.",
    legalStatus: "Schedule I (US federal). Legal: Oregon (supervised), Colorado (supervised), Jamaica, Netherlands (truffles), Brazil. Decriminalized: Denver, Oakland, Seattle, DC, and growing list of US cities.",
  },
  ayahuasca: {
    contraindications: [
      "Cardiovascular conditions (hypertension, arrhythmia, heart disease)",
      "Personal or family history of psychosis, schizophrenia, bipolar I",
      "Liver disease or hepatic impairment",
      "Pregnancy or breastfeeding",
      "Active seizure disorder",
      "Eating disorders (purging component can be triggering)",
    ],
    sideEffects: [
      "Intense vomiting and diarrhea (considered part of the 'purge' — expected)",
      "Elevated heart rate and blood pressure",
      "Intense emotional catharsis — terror, grief, ecstasy",
      "Temporary psychotic-like states during peak",
      "Physical exhaustion lasting 1–3 days",
      "Insomnia or vivid dreams for days after",
      "Rare: prolonged psychological disturbance",
    ],
    drugInteractions: [
      "SSRIs — LIFE-THREATENING serotonin syndrome risk; must taper off 2–6 weeks prior",
      "MAOIs (prescription) — DANGEROUS potentiation; absolute contraindication",
      "SNRIs (venlafaxine, duloxetine) — serotonin syndrome risk",
      "Tramadol — seizure and serotonin syndrome risk",
      "Lithium — seizure risk; absolute contraindication",
      "Stimulants (amphetamines, methylphenidate) — cardiovascular risk",
      "Tyramine-rich foods (aged cheese, cured meats, fermented foods) — hypertensive crisis",
      "St. John's Wort — serotonin syndrome risk",
    ],
    safetyWarning: "Ayahuasca carries the highest drug interaction risk of any psychedelic due to its MAO-inhibiting properties. The tyramine dietary protocol is NOT optional — it is a medical necessity. Deaths have occurred from SSRI combinations. Full medical screening and an experienced curandero are essential. This is not a casual experience.",
    legalStatus: "Schedule I (US — DMT component). Legal: Peru, Brazil, Ecuador, Colombia (traditional use). Religious exemption: Santo Daime and UDV churches (US, Netherlands). Costa Rica: unregulated.",
  },
  mdma: {
    contraindications: [
      "Cardiovascular disease, uncontrolled hypertension, or arrhythmia",
      "Liver or kidney disease",
      "History of stroke or cerebrovascular disease",
      "Bipolar I disorder or active psychosis",
      "Hyperthermia susceptibility",
      "Pregnancy or breastfeeding",
      "Glaucoma",
    ],
    sideEffects: [
      "Jaw clenching (bruxism) and teeth grinding",
      "Elevated body temperature (hyperthermia — can be dangerous)",
      "Dehydration and electrolyte imbalance",
      "Nausea during onset",
      "Post-session mood dip ('Tuesday blues') lasting 2–5 days",
      "Insomnia on night of session",
      "Temporary serotonin depletion",
      "Rare: hyponatremia from excessive water intake",
    ],
    drugInteractions: [
      "SSRIs — blocks MDMA effects AND serotonin syndrome risk",
      "MAOIs — LIFE-THREATENING serotonin syndrome; absolute contraindication",
      "Stimulants (amphetamines, cocaine) — dangerous cardiovascular strain",
      "Tramadol — seizure and serotonin syndrome risk",
      "CYP2D6 inhibitors — increased MDMA toxicity",
      "Alcohol — increased dehydration and neurotoxicity",
    ],
    safetyWarning: "MDMA's primary risks are cardiovascular and thermoregulatory. Temperature regulation, hydration (not over-hydration), and dosage precision are critical. Street 'ecstasy' frequently contains adulterants — reagent testing is essential. Therapeutic MDMA uses pharmaceutical-grade material in controlled settings.",
    legalStatus: "Schedule I (US). No legal therapeutic access yet (FDA rejected Lykos application 2024; revised trials underway). Legal research: MAPS trials. Australia: approved for supervised PTSD treatment (2023).",
  },
  ketamine: {
    contraindications: [
      "Uncontrolled hypertension",
      "Active psychosis or schizophrenia",
      "Elevated intracranial pressure",
      "Pregnancy or breastfeeding",
      "Active substance use disorder (ketamine itself has abuse potential)",
      "Severe liver disease",
      "Bladder conditions (chronic use causes cystitis)",
    ],
    sideEffects: [
      "Dissociation and derealization (expected therapeutic effect at proper dose)",
      "Nausea and vomiting",
      "Elevated blood pressure (transient)",
      "Dizziness and impaired coordination",
      "Vivid dreams or nightmares",
      "Bladder irritation with repeated use",
      "Psychological dependence risk with unsupervised use",
      "Rare: laryngospasm at high doses",
    ],
    drugInteractions: [
      "Benzodiazepines — reduce ketamine effects (sometimes used intentionally for anxiety)",
      "Opioids — respiratory depression risk at high doses",
      "MAOIs — hypertensive crisis risk",
      "Alcohol — dangerous CNS depression",
      "Lamotrigine — may reduce antidepressant effects of ketamine",
    ],
    safetyWarning: "Ketamine is the most accessible legal psychedelic option but carries real abuse potential. Unsupervised at-home use has led to dependence. Clinical supervision with integration therapy produces the best outcomes. Bladder damage is a serious risk with frequent recreational use. KAP-specific: IM injection administered by physician at 10\u201315mg starting dose, titrated per session. Sessions are 2 hours with 2\u20134 doses. Pre-session requirements: no alcohol/cannabis/substances 3 days prior, discuss all medications 72 hours before, no food 2 hours before, limit caffeine. Post-session: cannot drive 4\u20136 hours, rest for the day, journal while fresh, avoid major decisions 24 hours. Integration sessions (weekly/biweekly) are essential for lasting change.",
    legalStatus: "Schedule III (US) — legal with prescription. Spravato (esketamine) FDA-approved for treatment-resistant depression. Off-label IV infusions widely available. Legal in most countries with prescription.",
  },
  lsd: {
    contraindications: [
      "Personal or family history of psychosis, schizophrenia, or bipolar I",
      "Severe anxiety disorders without professional support",
      "Cardiovascular conditions (mild vasoconstriction)",
      "Pregnancy or breastfeeding",
      "Under 18 years of age",
    ],
    sideEffects: [
      "Anxiety or panic (especially at high doses or poor set/setting)",
      "Vasoconstriction (cold extremities, muscle tension)",
      "Insomnia (8–12 hour duration makes sleep difficult)",
      "Jaw tension and body load",
      "Emotional intensity — can surface repressed material",
      "Temporary confusion or thought loops",
      "Rare: HPPD (Hallucinogen Persisting Perception Disorder)",
      "Rare: prolonged psychotic episode in predisposed individuals",
    ],
    drugInteractions: [
      "SSRIs — significantly reduce effects",
      "Lithium — seizure risk; ABSOLUTE contraindication",
      "Tramadol — seizure risk",
      "MAOIs — unpredictable potentiation",
      "Cannabis — can dramatically intensify and destabilize the experience",
      "Antipsychotics — will terminate the experience (used as 'trip killer')",
    ],
    safetyWarning: "LSD's 8–12 hour duration demands psychological endurance. The long timeline means set, setting, and sitter quality matter enormously. Reagent-test all material (Ehrlich reagent). Start with conservative doses (50–75mcg). The experience cannot be stopped once started — only managed.",
    legalStatus: "Schedule I (US, most countries). No legal therapeutic access. Research: Switzerland (MIND Foundation), US clinical trials. Decriminalized in some US cities.",
  },
  dmt: {
    contraindications: [
      "Personal or family history of psychosis or schizophrenia",
      "Cardiovascular conditions (5-MeO-DMT causes significant BP spike)",
      "Respiratory conditions (smoked route)",
      "Pregnancy or breastfeeding",
      "No prior psychedelic experience (for 5-MeO-DMT especially)",
    ],
    sideEffects: [
      "Complete ego dissolution (5-MeO-DMT — can be terrifying)",
      "Elevated heart rate and blood pressure (especially 5-MeO)",
      "Nausea and vomiting (5-MeO-DMT)",
      "Intense emotional release — screaming, crying, convulsing",
      "Temporary amnesia of the experience",
      "Reactivation experiences days to weeks later",
      "Rare: prolonged dissociation or depersonalization",
    ],
    drugInteractions: [
      "SSRIs — serotonin syndrome risk (especially with 5-MeO-DMT)",
      "MAOIs — DANGEROUS with 5-MeO-DMT (unlike ayahuasca where MAOI is intentional)",
      "Lithium — seizure risk",
      "Stimulants — cardiovascular strain",
      "Cannabis — unpredictable potentiation",
    ],
    safetyWarning: "5-MeO-DMT is among the most intense psychedelic experiences possible. Deaths have occurred — primarily from physical complications during unmonitored sessions (aspiration, falls). A medical-grade facilitator, cardiac screening, and physical safety protocols are non-negotiable. Synthetic 5-MeO is recommended over wild-harvested toad secretion (conservation and consistency).",
    legalStatus: "Schedule I (US — N,N-DMT). 5-MeO-DMT: Schedule I (US). Legal: Mexico (5-MeO ceremonies), Brazil (ayahuasca context). Toad harvesting increasingly restricted.",
  },
  iboga: {
    contraindications: [
      "ANY cardiovascular condition — arrhythmia, QT prolongation, heart disease",
      "Liver disease or hepatic impairment",
      "Pregnancy or breastfeeding",
      "Active methadone or buprenorphine use (must taper 7–14 days prior)",
      "Seizure disorders",
      "Severe psychiatric conditions",
      "Eating disorders",
      "No prior psychedelic experience — whole-plant Iboga is not a starting point",
    ],
    sideEffects: [
      "Cardiac arrhythmia — QT prolongation (PRIMARY RISK)",
      "Extended duration: 36–72 hours with minimal sleep",
      "Intense nausea and purging (considered part of the healing in Bwiti tradition)",
      "Ataxia (loss of coordination) lasting 48–96 hours",
      "Vivid life-review visions — deeper and longer than ibogaine HCl",
      "Extreme physical weakness post-ceremony",
      "Liver enzyme elevation",
      "The full alkaloid profile may modulate cardiac risk differently than ibogaine HCl alone — research is ongoing",
    ],
    drugInteractions: [
      "Methadone — LIFE-THREATENING cardiac interaction; must be fully tapered",
      "Buprenorphine (Suboxone) — must taper 7–14 days prior",
      "SSRIs — serotonin syndrome risk; taper required",
      "Opioids — complex interaction; medical supervision essential",
      "Stimulants — cardiovascular danger",
      "Benzodiazepines — respiratory risk during extended session",
      "ANY QT-prolonging medication — absolute contraindication",
    ],
    safetyWarning: "Whole-plant Iboga (root bark) contains ibogaine PLUS 12+ companion alkaloids. The full-spectrum experience is longer (36–72 hrs vs 24–36 hrs for ibogaine HCl), deeper, and carries different risk profiles. Traditional Bwiti context with initiated N'ganga is strongly recommended. Full cardiac workup (12-lead ECG, liver panel, electrolytes) is MANDATORY. The companion alkaloids (ibogamine, tabernanthine, voacangine, noribogaine) are less studied than ibogaine alone.",
    legalStatus: "Schedule I (US — ibogaine is scheduled; whole-plant status varies). Legal: Gabon (traditional sacrament), Mexico, Brazil, New Zealand (prescription), Costa Rica (unregulated). Traditional Bwiti ceremonies in Gabon are culturally protected.",
  },
  ibogaine: {
    contraindications: [
      "ANY cardiovascular condition — arrhythmia, QT prolongation, heart disease",
      "Liver disease or hepatic impairment",
      "Pregnancy or breastfeeding",
      "Active methadone or buprenorphine use (must taper 7–14 days prior)",
      "Seizure disorders",
      "Severe psychiatric conditions",
      "Eating disorders",
    ],
    sideEffects: [
      "Cardiac arrhythmia — QT prolongation (PRIMARY RISK — deaths have occurred)",
      "Ataxia (loss of coordination) lasting 24–72 hours",
      "Intense nausea and vomiting",
      "24–36 hour duration with limited sleep",
      "Vivid life-review visions (can be deeply disturbing)",
      "Extreme physical weakness post-session",
      "Liver enzyme elevation",
      "Rare: cardiac arrest (estimated 1 in 300–400 without proper screening)",
    ],
    drugInteractions: [
      "Methadone — LIFE-THREATENING cardiac interaction; must be fully tapered",
      "Buprenorphine (Suboxone) — must taper 7+ days prior",
      "SSRIs — serotonin syndrome risk; taper required",
      "Opioids — complex interaction; medical supervision essential",
      "Stimulants — cardiovascular danger",
      "Benzodiazepines — respiratory risk during long session",
      "ANY QT-prolonging medication — absolute contraindication",
    ],
    safetyWarning: "Ibogaine HCl (the isolated alkaloid) has the highest fatality rate of any psychedelic medicine. Deaths are almost entirely cardiac — QT prolongation leading to fatal arrhythmia. FULL cardiac workup (12-lead ECG, liver panel, electrolytes, metabolic panel) is MANDATORY. Only use in medical facilities with cardiac monitoring, crash cart, and trained medical staff. Never in non-medical settings. Note: ibogaine HCl is the isolated molecule — distinct from whole-plant Iboga root bark used in Bwiti tradition.",
    legalStatus: "Schedule I (US). Legal: Mexico, Brazil, New Zealand (prescription), South Africa, Costa Rica (unregulated). Clinical trials: US (MAPS), Europe.",
  },
  mescaline: {
    contraindications: [
      "Personal or family history of psychosis or schizophrenia",
      "Cardiovascular conditions (sympathomimetic via \u03B11A/\u03B12A agonism)",
      "Pregnancy or breastfeeding",
      "Liver or kidney disease",
      "Under 18 years of age",
      "Active MAOI or lithium use \u2014 ABSOLUTE contraindication",
      "Concurrent SSRI use (reduced effects; serotonin interaction risk)",
    ],
    sideEffects: [
      "Intense nausea and vomiting (hours 1\u20133 \u2014 most common complaint)",
      "Elevated heart rate and blood pressure (adrenergic receptor agonism)",
      "Body temperature fluctuations",
      "Jaw tension and muscle discomfort",
      "Emotional intensity lasting 8\u201312 hours",
      "Physical exhaustion from long duration",
      "Headache post-experience",
      "Sympathomimetic arousal (\u03B11A/\u03B12A activation)",
    ],
    drugInteractions: [
      "SSRIs (Zoloft, Lexapro) \u2014 reduced effects; mescaline is a potential alternative per emerging research",
      "MAOIs \u2014 dangerous potentiation; absolute contraindication",
      "Lithium (Lithobid) \u2014 seizure risk; ABSOLUTE contraindication",
      "Tramadol \u2014 seizure risk",
      "Stimulants \u2014 cardiovascular strain",
      "Lurasidone (Latuda) \u2014 opposite receptor actions at 5-HT2A, D2, BDNF; discontinuation protocol required",
      "Quetiapine (Seroquel), Aripiprazole (Abilify) \u2014 will block psychedelic effects",
      "Buspirone (Buspar) \u2014 shared 5-HT1A pathway; interaction possible",
    ],
    safetyWarning: "Mescaline's 8\u201312 hour duration requires physical stamina and psychological endurance. Key pharmacology: 5-HT2A partial agonist (primary psychedelic), D1/D2/D3 low-affinity binding (prosocial), \u03B11A/\u03B12A agonist (sympathomimetic arousal), NO serotonin transporter affinity (unlike MDMA/SSRIs). Shares receptor targets with Latuda (lurasidone) but with opposite actions. Peyote is a protected sacrament for Native American Church members \u2014 non-indigenous use raises serious ethical and conservation concerns. San Pedro (Huachuma) is the more accessible and ethically appropriate option for non-indigenous seekers.",
    legalStatus: "Schedule I (US \u2014 mescaline). Peyote: legal for NAC members only. San Pedro cactus: legal to grow (ornamental), illegal to extract mescaline. Legal: Peru, Ecuador (traditional use).",
  },
  kambo: {
    contraindications: [
      "Cardiovascular conditions (hypertension, heart disease, arrhythmia)",
      "Addison's disease or adrenal insufficiency",
      "Epilepsy or seizure disorders",
      "Eating disorders (intense purging component)",
      "Pregnancy or breastfeeding",
      "Recent surgery or open wounds",
      "Mental health conditions involving dissociation",
      "Organ transplant recipients (immune activation)",
    ],
    sideEffects: [
      "Intense vomiting and diarrhea (expected — the 'purge')",
      "Facial swelling (frog face — temporary)",
      "Rapid heart rate and blood pressure changes",
      "Temporary loss of motor control",
      "Intense burning at application sites",
      "Fainting or syncope",
      "Rare: rhabdomyolysis (muscle breakdown)",
      "Rare: hyponatremia from excessive water intake during purge",
    ],
    drugInteractions: [
      "Blood pressure medications — unpredictable BP changes",
      "Immunosuppressants — kambo activates immune system",
      "Diuretics — electrolyte depletion risk",
      "Heart medications — cardiovascular instability",
    ],
    safetyWarning: "Kambo deaths have occurred — primarily from water intoxication (hyponatremia) and cardiac events. NEVER drink excessive water before or during kambo. An IAKP-certified practitioner who conducts health screening is essential. This is a physically intense ordeal medicine, not a gentle experience.",
    legalStatus: "Unscheduled in most countries. Legal in US, UK, most of Europe. Some Australian states restrict. Brazil: traditional indigenous use protected.",
  },
  rapeh: {
    contraindications: [
      "Nicotine sensitivity or allergy",
      "Severe respiratory conditions (asthma, COPD)",
      "Pregnancy or breastfeeding",
      "Nasal polyps or recent nasal surgery",
      "Cardiovascular conditions (nicotine is a stimulant)",
    ],
    sideEffects: [
      "Intense nasal burning and tearing (1–5 minutes)",
      "Nausea (especially first time)",
      "Dizziness and lightheadedness",
      "Sneezing and nasal discharge",
      "Mild headache",
      "Nicotine rush (can be intense for non-tobacco users)",
    ],
    drugInteractions: [
      "Nicotine patches/gum — nicotine overload",
      "Blood pressure medications — nicotine raises BP",
      "MAOIs — some rapeh blends contain MAOI herbs",
    ],
    safetyWarning: "Rapeh is generally low-risk but contains significant nicotine. First-time users should start with a very small dose. Authentic tribal preparations vary widely in strength. Not recommended for those with nicotine addiction history as it may trigger cravings.",
    legalStatus: "Legal in most countries. Unscheduled. Available as 'herbal snuff' in many jurisdictions.",
  },
  sananga: {
    contraindications: [
      "Eye infections or active eye conditions",
      "Recent eye surgery (LASIK, cataract, etc.)",
      "Glaucoma (consult ophthalmologist)",
      "Contact lens wearers (remove before application)",
      "Corneal abrasions or ulcers",
    ],
    sideEffects: [
      "Intense burning pain in eyes (3–10 minutes — expected)",
      "Profuse tearing",
      "Temporary blurred vision",
      "Emotional release (crying is common)",
      "Headache (rare)",
    ],
    drugInteractions: [
      "Eye medications — consult before combining",
      "No significant systemic drug interactions known",
    ],
    safetyWarning: "Sananga is one of the safest traditional medicines but the eye pain is intense and real. Always use authentic preparations from trusted sources — contaminated or improperly prepared sananga can cause eye damage. Remove contact lenses. Have a tissue ready.",
    legalStatus: "Legal worldwide. Unscheduled. Available as traditional eye drops.",
  },
  breathwork: {
    contraindications: [
      "Cardiovascular disease or uncontrolled hypertension",
      "History of seizures or epilepsy",
      "Pregnancy (especially third trimester)",
      "Retinal detachment or glaucoma",
      "Recent surgery",
      "Severe asthma (hyperventilation can trigger bronchospasm)",
    ],
    sideEffects: [
      "Tetany (muscle cramping, especially in hands — 'lobster claws')",
      "Dizziness and lightheadedness",
      "Tingling and numbness in extremities",
      "Emotional release — crying, screaming, shaking",
      "Temporary visual disturbances",
      "Nausea",
      "Rare: fainting",
    ],
    drugInteractions: [
      "No significant drug interactions (no substances involved)",
      "Beta-blockers may limit cardiovascular response",
    ],
    safetyWarning: "Breathwork is substance-free but produces real physiological changes through respiratory alkalosis. The tetany (hand cramping) is harmless but can be frightening. Always practice with a trained facilitator for the first time. Never practice near water or while driving.",
    legalStatus: "Legal everywhere. No regulatory restrictions. Certified facilitator training available through Grof Transpersonal Training.",
  },
  microdose: {
    contraindications: [
      "Personal or family history of psychosis (even at sub-perceptual doses)",
      "Bipolar disorder (may trigger manic episodes)",
      "Pregnancy or breastfeeding",
      "Color blindness screening recommended (visual changes)",
    ],
    sideEffects: [
      "Mild anxiety or restlessness on dose days",
      "Difficulty sleeping if dosed too late in the day",
      "Subtle emotional sensitivity",
      "Mild headache (especially with LSD microdose)",
      "Niacin flush if using Stamets Stack (harmless but uncomfortable)",
    ],
    drugInteractions: [
      "SSRIs — may reduce effects; serotonin interaction at sub-clinical level",
      "Lithium — seizure risk even at microdose levels; AVOID",
      "Tramadol — avoid",
    ],
    safetyWarning: "Microdosing is the lowest-risk entry point but is NOT risk-free. Doses should be truly sub-perceptual — if you feel 'high,' the dose is too high. Follow established protocols (Fadiman: 1 day on, 2 days off; Stamets: 4 days on, 3 days off). Track your experience in a journal.",
    legalStatus: "Illegal in most jurisdictions (psilocybin and LSD remain scheduled). Legal: Oregon (supervised psilocybin), Netherlands (truffles). Decriminalized in several US cities.",
  },
  cannabis: {
    contraindications: [
      "Personal or family history of psychosis or schizophrenia",
      "Adolescents under 25 (brain development concerns)",
      "Pregnancy or breastfeeding",
      "History of cannabis use disorder",
      "Severe anxiety disorders (THC can worsen)",
    ],
    sideEffects: [
      "Anxiety and paranoia (especially high-THC strains)",
      "Dry mouth and red eyes",
      "Impaired short-term memory",
      "Increased appetite",
      "Dizziness",
      "Drowsiness (indica-dominant)",
      "Rare: cannabis hyperemesis syndrome (chronic heavy use)",
    ],
    drugInteractions: [
      "Blood thinners (warfarin) — cannabis affects metabolism",
      "CNS depressants — increased sedation",
      "Psychedelics — can dramatically intensify and destabilize experiences",
      "Some blood pressure medications",
    ],
    safetyWarning: "Cannabis is widely available and culturally normalized but carries real risks, especially for those predisposed to psychosis. High-THC strains are significantly more potent than historical cannabis. Start low, go slow. CBD-dominant strains are safer for anxiety-prone individuals.",
    legalStatus: "Legal (recreational): 24 US states, Canada, Uruguay, Germany, Thailand. Medical: 38 US states, most of EU. Schedule I (US federal — rescheduling pending).",
  },
  cacao: {
    contraindications: [
      "Caffeine sensitivity (theobromine is a mild stimulant)",
      "Heart conditions (large ceremonial doses elevate heart rate mildly)",
      "Taking antidepressants (theobromine has mild MAOI properties at high doses)",
      "Migraine sufferers (chocolate is a common trigger)",
    ],
    sideEffects: [
      "Mild nausea at ceremonial doses (40–50g)",
      "Headache (especially if dehydrated)",
      "Jitteriness (similar to coffee)",
      "Emotional sensitivity and tearfulness",
      "Mild digestive discomfort",
    ],
    drugInteractions: [
      "MAOIs — theobromine has mild MAOI properties; caution at high doses",
      "Stimulants — additive stimulant effect",
      "Generally very safe with most medications",
    ],
    safetyWarning: "Ceremonial cacao is one of the safest substances in this pharmacopoeia. The main risk is overconsumption leading to nausea or headache. Use ceremonial-grade cacao (not processed chocolate). Stay hydrated.",
    legalStatus: "Legal worldwide. No restrictions. Available as food product.",
  },
  amanita: {
    contraindications: [
      "Liver disease (muscimol is hepatically processed)",
      "Kidney disease",
      "Pregnancy or breastfeeding",
      "Children",
      "History of seizures",
      "Anyone unable to properly identify mushroom species",
    ],
    sideEffects: [
      "Nausea and vomiting (common)",
      "Drowsiness and sedation (muscimol is GABAergic)",
      "Ataxia (loss of coordination)",
      "Confusion and delirium",
      "Muscle twitching",
      "Salivation and sweating",
      "Rare: seizures at high doses",
      "DANGER: Misidentification with Amanita phalloides (death cap) is FATAL",
    ],
    drugInteractions: [
      "Benzodiazepines — additive GABAergic sedation",
      "Alcohol — dangerous CNS depression",
      "Opioids — respiratory depression risk",
      "Anticonvulsants — unpredictable interaction",
    ],
    safetyWarning: "Amanita muscaria is NOT in the same safety class as psilocybin mushrooms. The margin between active and toxic dose is narrow. Misidentification with deadly Amanita species (A. phalloides, A. ocreata) kills people every year. NEVER forage without expert mycological identification. Proper preparation (decarboxylation of ibotenic acid to muscimol) is essential.",
    legalStatus: "Legal in most countries (not a controlled substance). Unscheduled in US. Illegal: Louisiana, Netherlands. Legal to possess and sell in most jurisdictions.",
  },
  huachuma: {
    contraindications: [
      "Personal or family history of psychosis or schizophrenia",
      "Cardiovascular conditions",
      "Pregnancy or breastfeeding",
      "Liver or kidney disease",
    ],
    sideEffects: [
      "Intense nausea and vomiting (first 1–2 hours)",
      "Elevated heart rate",
      "Body temperature fluctuations",
      "Physical exhaustion (8–14 hour duration)",
      "Emotional intensity",
      "Jaw tension",
    ],
    drugInteractions: [
      "SSRIs — reduced effects",
      "MAOIs — dangerous potentiation",
      "Lithium — seizure risk",
      "Tramadol — seizure risk",
    ],
    safetyWarning: "Huachuma (San Pedro) is considered gentler than ayahuasca but the 8–14 hour duration requires stamina. Outdoor daytime ceremonies are traditional and recommended. The nausea phase is significant — prepare for it. Heart screening is recommended for high doses.",
    legalStatus: "Legal to grow as ornamental cactus (US, most countries). Illegal to extract mescaline. Legal traditional use: Peru, Ecuador, Bolivia.",
  },
  salvia: {
    contraindications: [
      "History of psychosis or dissociative disorders",
      "Severe anxiety disorders",
      "Pregnancy or breastfeeding",
      "Under 18 years of age",
    ],
    sideEffects: [
      "Intense dissociation and reality fracturing (can be terrifying)",
      "Loss of body awareness and motor control",
      "Dysphoria (many find the experience unpleasant)",
      "Confusion and disorientation",
      "Sweating",
      "Rare: persistent anxiety after use",
    ],
    drugInteractions: [
      "Limited research on interactions",
      "CNS depressants — additive dissociation",
      "Kappa-opioid active medications — unpredictable",
    ],
    safetyWarning: "Salvia divinorum is legal in many places but is NOT a recreational substance. The experience is frequently described as terrifying and dysphoric. Complete loss of motor control means a sitter is MANDATORY. Traditional Mazatec use (fresh leaf quid) is far gentler than concentrated extracts. Smoked extracts (5x, 10x, 20x) are extremely intense and NOT recommended for beginners.",
    legalStatus: "Legal in most US states (exceptions: Delaware, Florida, Hawaii, Illinois, others). Unscheduled federally. Banned in several countries (Australia, Belgium, Denmark, others).",
  },
  yopo: {
    contraindications: [
      "Cardiovascular conditions",
      "Respiratory conditions (nasal administration is harsh)",
      "Personal or family history of psychosis",
      "Pregnancy or breastfeeding",
      "Nasal conditions or recent nasal surgery",
    ],
    sideEffects: [
      "Intense nasal pain and burning",
      "Profuse nasal discharge and tearing",
      "Nausea and vomiting",
      "Elevated heart rate and blood pressure",
      "Intense psychedelic effects (20–45 min)",
      "Physical discomfort and body load",
      "Headache post-experience",
    ],
    drugInteractions: [
      "SSRIs — serotonin syndrome risk (contains DMT and 5-MeO-DMT)",
      "MAOIs — dangerous potentiation",
      "Lithium — seizure risk",
      "Stimulants — cardiovascular strain",
    ],
    safetyWarning: "Yopo is physically demanding — the nasal administration causes significant pain and the psychedelic onset is rapid and intense. The combination of bufotenine, DMT, and 5-MeO-DMT makes this a complex pharmacological experience. Only with experienced facilitators in appropriate ceremonial context.",
    legalStatus: "Seeds: legal in most countries (not specifically scheduled). Active compounds (DMT, 5-MeO-DMT): Schedule I (US). Traditional use: legal in South America.",
  },
  lionsmane: {
    contraindications: [
      "Mushroom allergies",
      "Bleeding disorders (may have anticoagulant properties)",
      "Upcoming surgery (discontinue 2 weeks prior)",
    ],
    sideEffects: [
      "Mild digestive discomfort (rare)",
      "Skin rash in those with mushroom sensitivities",
      "Niacin flush if using Stamets Stack (harmless but uncomfortable)",
    ],
    drugInteractions: [
      "Blood thinners — may enhance anticoagulant effects",
      "Diabetes medications — may lower blood sugar",
      "Generally very safe with most medications",
    ],
    safetyWarning: "Lion's Mane is a food-grade medicinal mushroom with an excellent safety profile. It is not psychoactive. The primary consideration is product quality — choose dual-extracted (hot water + alcohol) products from fruiting bodies, not mycelium-on-grain.",
    legalStatus: "Legal worldwide. Dietary supplement. No restrictions anywhere.",
  },
  ibogamic: {
    contraindications: [
      "Cardiovascular conditions (reduced risk vs. flood dose but still present)",
      "Liver disease",
      "Pregnancy or breastfeeding",
      "Active methadone or buprenorphine use",
    ],
    sideEffects: [
      "Mild stimulation and wakefulness",
      "Reduced appetite",
      "Vivid dreams",
      "Mild nausea",
      "Emotional processing",
    ],
    drugInteractions: [
      "Methadone — cardiac interaction risk (reduced vs. flood but still present)",
      "SSRIs — serotonin interaction",
      "QT-prolonging medications — caution",
      "Stimulants — additive stimulation",
    ],
    safetyWarning: "Sub-flood iboga doses carry significantly lower cardiac risk than flood doses but are NOT risk-free. Cardiac awareness and monitoring are still recommended. Best used under supervision, especially for those in addiction recovery. The stimulant properties can disrupt sleep if taken too late in the day.",
    legalStatus: "Schedule I (US — ibogaine). Same legal status as full-dose ibogaine. Legal: Mexico, Brazil, New Zealand (prescription).",
  },
  changa: {
    contraindications: [
      "Personal or family history of psychosis",
      "Cardiovascular conditions",
      "Respiratory conditions",
      "Pregnancy or breastfeeding",
      "No prior psychedelic experience",
    ],
    sideEffects: [
      "Intense psychedelic visionary state (20–45 min)",
      "Nausea",
      "Elevated heart rate",
      "Emotional intensity",
      "Coughing from smoke inhalation",
      "Reactivation experiences",
    ],
    drugInteractions: [
      "SSRIs — serotonin syndrome risk (MAOI component)",
      "MAOIs (prescription) — dangerous potentiation",
      "Tyramine-rich foods — hypertensive crisis (MAOI component)",
      "Lithium — seizure risk",
      "Tramadol — seizure risk",
    ],
    safetyWarning: "Changa contains MAOI herbs — the same drug interaction risks as ayahuasca apply. The tyramine dietary protocol should be observed. Despite the shorter duration, the intensity can match ayahuasca. Prior psychedelic experience is strongly recommended.",
    legalStatus: "Schedule I (US — DMT component). Legal: Netherlands. Illegal in most countries due to DMT content.",
  },
  caapi: {
    contraindications: [
      "Cardiovascular conditions",
      "Liver disease",
      "Pregnancy or breastfeeding",
      "Active psychiatric crisis",
    ],
    sideEffects: [
      "Nausea and purging (milder than full ayahuasca)",
      "Drowsiness and sedation",
      "Vivid dreams",
      "Emotional sensitivity",
      "Mild visual effects in darkness",
    ],
    drugInteractions: [
      "SSRIs — serotonin syndrome risk (vine is an MAOI)",
      "MAOIs (prescription) — dangerous potentiation",
      "Tyramine-rich foods — hypertensive crisis",
      "Tramadol — seizure and serotonin syndrome risk",
      "Stimulants — cardiovascular risk",
    ],
    safetyWarning: "Caapi vine alone is gentler than full ayahuasca but retains ALL the MAOI drug interaction risks. The tyramine dietary protocol is still required. SSRIs must still be tapered. Do not assume 'vine only' means 'safe with medications.'",
    legalStatus: "Legal in most countries (the vine itself is not scheduled — DMT is). Legal to purchase and brew in US, EU. The vine is the legal component of ayahuasca.",
  },
  soma: {
    contraindications: [
      "Depends entirely on the specific preparation (identity debated)",
      "Cardiovascular conditions (if Ephedra-based)",
      "Liver conditions (if Amanita-based)",
      "Pregnancy or breastfeeding",
    ],
    sideEffects: [
      "Varies by preparation",
      "If Amanita-based: see Amanita muscaria entry",
      "If Ephedra-based: stimulant effects, cardiovascular strain",
      "If Peganum harmala-based: MAOI effects, nausea",
    ],
    drugInteractions: [
      "Depends on preparation — could include MAOI interactions",
      "Consult specific ingredient safety profiles",
    ],
    safetyWarning: "The identity of Soma is academically debated. Modern 'Soma preparations' vary wildly in composition. There is NO standardized formula. Approach any reconstructed Soma preparation with extreme caution — verify every ingredient and its interaction profile independently.",
    legalStatus: "Varies by preparation ingredients. No specific 'Soma' scheduling exists. Individual components may be scheduled.",
  },
  mapacho: {
    contraindications: [
      "Nicotine sensitivity or allergy",
      "Cardiovascular conditions (high nicotine content)",
      "Pregnancy or breastfeeding",
      "Nicotine addiction (may trigger relapse)",
      "Respiratory conditions (if smoked)",
    ],
    sideEffects: [
      "Intense nicotine rush (20x commercial tobacco)",
      "Nausea and vomiting (especially when drunk as vomitivo)",
      "Dizziness and lightheadedness",
      "Elevated heart rate and blood pressure",
      "Sweating",
    ],
    drugInteractions: [
      "Nicotine replacement therapy — nicotine overload",
      "Blood pressure medications — nicotine raises BP",
      "MAOIs — tobacco contains natural MAOIs; interaction risk",
    ],
    safetyWarning: "Mapacho contains 20x the nicotine of commercial tobacco. Nicotine poisoning is possible with improper dosing, especially when consumed as liquid (vomitivo). This is a facilitator-administered medicine — do not self-administer without guidance. Despite being 'just tobacco,' the potency demands respect.",
    legalStatus: "Legal worldwide. Tobacco product. No restrictions beyond standard tobacco regulations.",
  },
};
